import test from 'node:test';
import assert from 'node:assert/strict';
import {validateExpression,validateStrategy,validateFactor} from '../edge/validation.mjs';
export const strategy={schemaVersion:1,name:'测试研究',universe:{symbols:['000001.SZ','000002.SZ','600000.SH'],start:'20230101',end:'20260930'},factors:[{id:'momentum_20',expression:'returns(close,20)',direction:1}],preprocess:{winsorize:true,standardize:true},model:{mode:'auto',candidates:['factor_score','ridge'],horizon:5,metric:'rank_ic'},portfolio:{topN:2,maxWeight:.4,rebalanceDays:5,initialCapital:1000000},costs:{commissionBps:3,slippageBps:10,sellTaxBps:5},graph:{nodes:[],edges:[]}};
test('causal DSL accepts nested math and detects lookback/dependencies',()=>{assert.deepEqual(validateExpression('rank(returns(close,20)) / max(ts_std(returns(close,1),20),0.001)').fields,['close']);assert.equal(validateExpression('lag(ts_mean(close,20),5)').lookback,24);});
test('DSL rejects future windows/code/properties and noncausal syntax',()=>{for(const e of ['lag(close,-1)','returns(close,0)','ts_mean(close,999)','__import__(close)','close.constructor','close[0]','close**2','fetch(close)','1','clip(close,2,1)','close;close','returns(close,1,2)','close = 5'])assert.throws(()=>validateExpression(e),undefined,e);});
test('strategy bounds, dates, model choice and costs enforced',()=>{assert.equal(validateStrategy(strategy).universe.symbols.length,3);for(const patch of [{universe:{...strategy.universe,start:'20230230'}},{model:{...strategy.model,candidates:['fake_ai']}},{costs:{...strategy.costs,slippageBps:-1}},{factors:[{id:'x',expression:'lag(close,-1)'}]}])assert.throws(()=>validateStrategy({...strategy,...patch}));});
test('community contribution requires explicit open license and safe source',()=>{const f={name:'动量',description:'示例',expression:'returns(close,20)',license:'MIT',author:'User'};assert.equal(validateFactor(f).metadata.validation,'syntax_validated');assert.throws(()=>validateFactor({...f,license:'proprietary'}));assert.throws(()=>validateFactor({...f,sourceUrl:'javascript:alert(1)'}));});
test('strategy projection strips arbitrary credential-like metadata and rejects object versions',()=>{const input=structuredClone(strategy);input.token='marker';input.universe.authorization='marker';input.model.password='marker';input.factors[0].serviceToken='marker';input.graph={nodes:[],edges:[],api_key:'marker'};assert.ok(!JSON.stringify(validateStrategy(input)).includes('marker'));input.factors[0].version={token:'marker'};assert.throws(()=>validateStrategy(input));assert.equal(input.universe.authorization,'marker');});
