/* Frontend contract tests with explicit fixtures, no provider calls or deployments. */
import fs from 'node:fs/promises';
import vm from 'node:vm';
import assert from 'node:assert/strict';

const handlers={},elements=new Map(),storage=new Map(),requests=[];
const node=()=>({innerHTML:'',style:{},append(){},remove(){},classList:{contains:()=>false},addEventListener(){},focus(){}});
for(const id of ['#app','#toast-root','#modal-root'])elements.set(id,node());
const document={querySelector:id=>elements.get(id)||null,querySelectorAll:()=>[],addEventListener:(event,fn)=>(handlers[event]||=[]).push(fn),createElement:node,body:node(),getElementById:id=>elements.get('#'+id)||null,hidden:false};
const symbols=Array.from({length:1000},(_,n)=>String(600000+n)+'.SH');
const members=symbols.map((ts_code,n)=>({ts_code,name:'测试成员 '+n,area:n<80?'北京':'广东',industry:'测试行业',exchange:'SSE'}));
const fixture={schemaVersion:1,fields:[{field:'universe',label:'股票池',kind:'universe',values:[{value:'csi1000',label:'测试中证1000',count:1000}]},{field:'area',label:'地域',values:[{value:'北京',label:'北京',count:80},{value:'广东',label:'广东',count:920}]},{field:'exchange',label:'交易所',values:[{value:'SSE',label:'上交所',count:1000}]}]};
function resolveSet(selection){let result=selection.includeGroups.length?members.filter(m=>selection.includeGroups.some(g=>g.filters.every(f=>{const values=Array.isArray(f.value)?f.value:[f.value];return f.field==='universe'?values.includes('csi1000'):values.includes(m[f.field]);}))):[];const selected=new Set([...result.map(x=>x.ts_code),...selection.includeSymbols]);for(const m of members)if(selection.excludeGroups.some(g=>g.filters.every(f=>(Array.isArray(f.value)?f.value:[f.value]).includes(m[f.field]))))selected.delete(m.ts_code);selection.excludeSymbols.forEach(x=>selected.delete(x));const values=[...selected].sort();return {selection, symbols:values,members:members.filter(x=>selected.has(x.ts_code)),symbolCount:values.length,resolutionHash:'resolution-fixture',snapshotHash:'snapshot-fixture',catalogSnapshot:{hash:'snapshot-fixture',asOf:'20261008'},steps:[{stage:'final',before:1000,after:values.length}],requiresSubset:values.length>50,historicalMembershipVerified:false};}
const context={document,location:{hash:'#research/universe',origin:'http://localhost'},localStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v)},setTimeout:()=>1,clearTimeout(){},setInterval(){},AbortController,AbortSignal,URL,URLSearchParams,TextEncoder,TextDecoder,Blob,console,window:{addEventListener(){}},fetch:async(url,options={})=>{const path=new URL(url,'http://localhost').pathname,body=options.body?JSON.parse(options.body):null;requests.push({path,body});let data;if(path.endsWith('/session'))data={capabilities:{tushareHosted:true},runner:{online:true}};else if(path.endsWith('/universe-options'))data=fixture;else if(path.endsWith('/universes/csi1000'))data={id:'csi1000',name:'测试中证1000',symbols,symbolCount:1000,availability:{status:'ready'},recommendedSymbols:symbols.slice(0,20)};else if(path.endsWith('/universes/resolve'))data=resolveSet(body.selection);else if(path.endsWith('/universes'))data={items:[],total:0,categories:[]};else if(path.endsWith('/factor-catalog'))data={items:[],total:0};else if(path.endsWith('/research-presets'))data={goals:[],packs:[],strategies:[]};else data={items:[]};return {ok:true,status:200,text:async()=>JSON.stringify(data)};}};
context.window.location=context.location;context.window.document=document;vm.createContext(context);
for(const file of ['research-workflow.js','studio.js'])vm.runInContext(await fs.readFile(new URL('../'+file,import.meta.url),'utf8'),context);
let app=await fs.readFile(new URL('../app.js',import.meta.url),'utf8');app=app.replace('  init();','  globalThis.qa={state,studio,normalizeStrategy,validateStrategy,statArbReport,statArbSignals,statArbFits,reportBody,parseRoute,api,render,baseStrategy};');vm.runInContext(app,context);
const q=context.qa,f=q.studio.flow,t=f.__test;let checked=0;
const check=(name,fn)=>{fn();checked++;console.log('PASS '+name);};
q.state.session={capabilities:{tushareHosted:true},runner:{online:true}};q.state.loading=false;
await f.initialize();
check('new research has no implicit members, uses stat_arb and explicit cost defaults',()=>{assert.equal(q.state.strategy.research.mode,'stat_arb');assert.equal(q.state.strategy.universe.symbols.length,0);assert.equal(q.state.strategy.factors.length,0);assert.equal(q.state.strategy.costs.minCommission,5);});
await f.selectUniverse('csi1000');
check('1000 full members resolve without auto choosing recommended20',()=>{assert.equal(t.u.resolution.symbolCount,1000);assert.equal(q.state.strategy.universe.symbols.length,0);assert.equal(t.u.resolution.members.length,1000);assert.equal(q.state.strategy.universe.snapshotHash,'snapshot-fixture');});
check('full member grid paginates40 rather than1000 DOM inputs',()=>{assert.equal((t.memberSelection().match(/data-rq-member=/g)||[]).length,40);});
check('full pool cannot be applied when over50',()=>{assert.throws(()=>t.setSubset(symbols,'all'),/3–50/);});
await f.handle({dataset:{v2:'pool-take'}});
check('explicit sample button records20 selected and explicit policy',()=>{assert.equal(q.state.strategy.universe.symbols.length,20);assert.equal(q.state.strategy.universe.subsetPolicy,'explicit');assert.equal(q.validateStrategy(false).length,0);});
const group=t.selection().includeGroups[0];
await f.handle({dataset:{v2:'pool-add-filter',id:group.id,scope:'includeGroups'}});
check('changing collection clears old confirmed subset and snapshot',()=>{assert.equal(q.state.strategy.universe.symbols.length,0);assert.equal(q.state.strategy.universe.snapshotHash,undefined);assert(q.validateStrategy(false).some(x=>x.includes('重新计算')));});
f.onChange({dataset:{rqValue:group.id,scope:'includeGroups',index:'1'},multiple:true,selectedOptions:[{value:'北京'}]});
await t.resolve();
check('AND geographic filter resolves complete80 and still needs explicit subset',()=>{assert.equal(t.u.resolution.symbolCount,80);assert.equal(q.state.strategy.universe.symbols.length,0);assert.equal(requests.at(-1).body.selection.includeGroups[0].filters[1].field,'area');});
await f.handle({dataset:{v2:'pool-take'}});
check('outside-set manual additions are rejected',()=>{assert.throws(()=>t.setSubset(['600000.SH','600001.SH','600999.SH'],'explicit'),/不在当前集合/);});
for(const [step] of t.steps){context.location.hash='#research/'+step;q.parseRoute();const html=q.studio.render();check('independent route '+step,()=>{assert.equal(q.state.researchStep,step);assert(html.includes('aria-current="step"'));assert(!html.includes('[object Object]'));assert(!html.includes('旧版持仓数 Top N'));assert(html.includes('rq-pagination'));});}
check('signals separate observation, holding and residual entry/exit parameters',()=>{const h=t.signalPage();for(const key of ['research.observationDays','statArb.maxHoldingDays','statArb.entryZ','statArb.exitZ','statArb.stopZ','preprocess.decorrelation'])assert(h.includes('data-config="'+key+'"'));});
check('execution exposes cadence, basket band, borrowing and minimum commission',()=>{const h=t.executionPage();for(const key of ['portfolio.rebalanceDays','portfolio.rebalanceThresholdBps','statArb.borrowAnnualBps','costs.minCommission','costs.transferBps'])assert(h.includes('data-config="'+key+'"'));assert(!h.includes('Top N'));});
check('threshold relationships are enforced before run',()=>{const a=q.state.strategy.statArb;a.exitZ=3;assert(q.validateStrategy(false).some(x=>x.includes('离场 < 入场')));a.exitZ=.5;a.residualWindow=200;assert(q.validateStrategy(false).some(x=>x.includes('残差窗口不可')));a.residualWindow=60;});
check('zero-factor baseline is accepted while factor-residual needs factors',()=>{q.state.strategy.statArb.method='factor_residual';assert(q.validateStrategy(false).some(x=>x.includes('至少需要一个')));q.state.strategy.statArb.method='pca_residual';assert.equal(q.validateStrategy(false).length,0);});
const prior=q.state.strategy,old={schemaVersion:1,name:'旧长仓',universe:{symbols:symbols.slice(0,5),start:'20230101',end:'20260930'},factors:[{id:'momentum_20',expression:'returns(close,20)',direction:1}],model:{mode:'auto',candidates:['ridge','elastic_net'],horizon:5},costs:{commissionBps:0,slippageBps:0,sellTaxBps:0}};
q.state.strategy=q.normalizeStrategy(old);
check('legacy records keep original candidate families and zero fees',()=>{assert.equal(q.state.strategy.research.mode,'legacy_long_only');assert.equal(q.state.strategy.costs.minCommission,0);assert.equal(q.state.strategy.costs.transferBps,0);assert.equal(q.state.strategy.costs.slippageBps,0);assert.deepEqual(Array.from(q.state.strategy.model.candidates),['ridge','elastic_net']);assert(t.executionPage().includes('旧版持仓数 Top N'));assert(!t.signalPage().includes('statArb.entryZ'));});
check('switching saved strategies does not leak previous pool rules',()=>{assert.equal(t.selection().includeGroups.length,0);assert.equal(t.u.resolution,null);});
q.state.strategy=prior;
for(const step of ['data','factors','targets','models','validation','portfolio','reports','code']){q.state.view='studio';q.state.studioStep=step;const h=q.studio.render();check('Studio '+step+' remains independently renderable',()=>{assert(h.includes('<h1>'));assert(!h.includes('[object Object]'));});}
const metric={totalReturn:.01,sharpe:.3,maxDrawdown:-.1,totalCosts:111,tradeCount:30,turnover:4,costBreakdown:{commission:10,slippage:20,tax:30,transfer:1,borrow:50}};
const report={strategy:q.state.strategy,research:{mode:'stat_arb'},metrics:metric,provenance:{},selection:{evidenceStatus:'UNVALIDATED_THEORETICAL_STAT_ARB'},equity:[{date:'20260101',equity:1e6,benchmark:1e6},{date:'20260201',equity:101e4,benchmark:1e6}],statArb:{method:'pca_residual',configuration:q.state.strategy.statArb,modelFits:Array.from({length:23},(_,n)=>({id:n,signalDate:'20260101',formationStart:'20250601',formationEnd:'20251231',exposures:['dollar_intercept','PC1'],dropped:[],residualDegreesOfFreedom:18,projectionNetError:1e-10,loadings:[],symbols:[]})),signals:{rows:Array.from({length:123},(_,n)=>({date:'20260101',symbol:symbols[n%20],zScore:n===0?null:1.2,halfLifeSessions:null,ar1:.8,state:1,reason:'hold',modelFitId:1})),latest:[],stateCounts:{hold:123},totalRows:123,truncated:false},evidence:{parametersPredeclared:true,shortInventoryVerified:false,cointegrationTestPerformed:false,finalHoldout:{start:'20260101',end:'20260201'}},exposure:{targetGross:1,targetNet:0,maxAbsoluteRealizedNet:.01,maxRealizedGross:1.2},baselineComparison:{baselineMethod:'pca_residual',sameUniverse:true,sameCosts:true,sameHoldout:true,parameterRetuning:false,baselineMetrics:metric,extendedMetrics:metric,deltaNetReturn:0,deltaSharpe:0},costComparison:{net:metric,zeroCostCounterfactual:metric,deltaReturn:0,sameSignalSchedule:true}},trades:[]};
for(const tab of ['overview','signals','fits','trades','provenance']){q.state.reportTab=tab;const h=q.reportBody(report,'tushare');check('stat-arb report '+tab+' uses actual schema without prediction UI',()=>{assert(!h.includes('本次模型选择'));assert(!h.includes('逐股预测'));assert(!h.includes('[object Object]'));assert(!h.includes('NaN'));assert(h.includes('理论多空'));});}
q.state.arbSignalScope='all';check('signal report limits row rendering to50',()=>{assert.equal((q.statArbSignals(report).match(/<tr>/g)||[]).length,51);});
check('fit report paginates20 and renders precise audit fields',()=>{assert.equal((q.statArbFits(report).match(/<tr>/g)||[]).length,21);assert(q.statArbFits(report).includes('载荷矩阵'));});
console.log(JSON.stringify({passed:checked,fixtureOnly:true,fullPool:1000,renderedMembers:40,renderedSignals:50}));
