/** Real DOM input/click events. API responses here are explicit unit-test doubles, not provider evidence. */
import assert from 'node:assert/strict';
import {build} from 'esbuild';
import fs from 'node:fs/promises';
import {JSDOM} from 'jsdom';
const dom=new JSDOM('<a class="skip-link" href="#main-content">跳过导航</a><div id="app"></div><div id="toast-root"></div><div id="modal-root"></div>',{url:'http://localhost/quant/#quant/universe',runScripts:'outside-only',pretendToBeVisual:true});
const w=dom.window;w.scrollTo=(x,y)=>{Object.defineProperty(w,'scrollX',{configurable:true,value:x});Object.defineProperty(w,'scrollY',{configurable:true,value:y});};const mediaListeners=[];const media={matches:false,addEventListener(_event,listener){mediaListeners.push(listener);}};w.matchMedia=()=>media;const viewport=matches=>{media.matches=matches;mediaListeners.forEach(fn=>fn({matches}));};w.structuredClone=structuredClone;
let saved=[],executionPayload,failedPath='',comparisonPayload,savedComparison,comparisonReads=0,forecastFixtureOverride=null,historyFixtureOverride=null;const gates=new Map();const hold=part=>{let release;const promise=new Promise(resolve=>release=resolve);gates.set(part,promise);return ()=>{gates.delete(part);release();};};
w.fetch=async(url,opt={})=>{const path=String(url);const waiting=[...gates].find(([part])=>path.includes(part));if(waiting)await waiting[1];if(failedPath&&path.includes(failedPath))throw Error('QA 网络中断');const data=opt.body?JSON.parse(opt.body):null;let result={items:[],total:0};if(path.includes('/experiments')&&opt.method==='POST'){result={experiment:{id:'experiment-test',version:1,name:data.strategy.name,strategy:data.strategy}};saved.push(data.strategy);}if(path.includes('/universes?'))result={items:[{id:'mock-csi300',name:'测试沪深300目录',category:'index',symbolCount:300,availability:{status:'ready'}}],total:1,categories:['index']};if(path.endsWith('/universes/mock-csi300'))result={item:{id:'mock-csi300',name:'测试沪深300目录',availability:{status:'ready'}}};if(path.endsWith('/code/review'))result={review:{providerExecuted:true,provider:'API DOUBLE ONLY',model:'test-model',codeSha256:'d'.repeat(64),reviewedAt:'2026-10-08T00:00:00Z',summary:'模拟接口审阅',findings:[],patches:[]}};if(path.endsWith('/universes/resolve'))result={selection:data.selection,symbols:['600000.SH'],members:[{ts_code:'600000.SH'}],symbolCount:1,snapshotHash:'a'.repeat(64),resolutionHash:'b'.repeat(64),catalogSnapshot:{hash:'a'.repeat(64),asOf:'2026-10-08',historicalMembershipVerified:false,securityCount:6000,universeCount:1000},steps:[]};if(path.includes('/factor-catalog?'))result={items:[{id:'dom-momentum',name:'DOM momentum',expression:'returns(close,5)',direction:1,availability:{status:'ready'}},{id:'dom-unavailable',name:'DOM unavailable',expression:'pcd_unavailable',availability:{status:'needs_mapping'},requiredFields:['pcd_unavailable']}],total:2};if(path.includes('/modules'))result={items:[],total:0};if(path.includes('/executions')&&opt.method==='POST'){executionPayload=data;result={job:{id:'execution-test',status:'queued'}};}if(path.includes('/statistical-quant/forecasts?'))result={items:[{id:'forecast-test-a',metadata:{target:{kind:'asset_price'},model:{family:'mean_reversion'}}},{id:'forecast-test-b',metadata:{target:{kind:'asset_price'},model:{family:'trend'}}}],total:2};if(path.endsWith('/statistical-quant/comparisons')&&opt.method==='POST'){comparisonPayload=data;savedComparison={id:'comparison-test',name:data.name,kind:data.kind,members:data.members,controlledComparison:false,items:data.members.map(id=>({id,diagnostics:{metrics:{rmse:.2,noChangeMse:.1,mseImprovement:-.02}}}))};result={comparison:savedComparison};}if(path.includes('/statistical-quant/comparisons?'))result={items:savedComparison?[savedComparison]:[],total:savedComparison?1:0};if(path.endsWith('/statistical-quant/comparisons/comparison-test')){comparisonReads++;result={comparison:savedComparison};}
if(path.includes('/statistical-quant/forecasts?')&&forecastFixtureOverride)result={items:forecastFixtureOverride,total:forecastFixtureOverride.length};if(path.includes('/statistical-quant/comparisons?')&&historyFixtureOverride)result={items:historyFixtureOverride,total:historyFixtureOverride.length};if(path.endsWith('/statistical-quant/experiments/fresh-detail'))result={experiment:{id:'fresh-detail',name:'新研究详情',version:1,strategy:saved[0]},runs:[]};if(path.endsWith('/runs/failed-readback/report'))result={job:{id:'failed-readback',status:'cancelled'}};return {ok:true,status:200,text:async()=>JSON.stringify(result)};};
const result=await build({entryPoints:['web/main.js'],bundle:true,write:false,format:'iife',plugins:[{name:'qa-no-init',setup(b){b.onLoad({filter:/\/web\/app\.js$/},async a=>({contents:(await fs.readFile(a.path,'utf8')).replace('  init();','  window.qa={state,studio,workspace,parseRoute,render,validateStrategy};'),loader:'js'}));}}]});
w.eval(result.outputFiles[0].text);const q=w.qa,s=q.state;s.loading=false;s.session={capabilities:{tushareHosted:true},runner:{online:true}};q.parseRoute();q.render();
const tick=()=>new Promise(r=>setTimeout(r,35));
const route=async page=>{w.location.hash='#quant/'+page;await tick();};
const input=(path,value)=>{const el=w.document.querySelector(`[data-sq-config="${path}"]`);assert(el,`exists ${path}`);el.focus();el.value=value;el.dispatchEvent(new w.InputEvent('input',{bubbles:true}));return el;};
assert.equal(s.strategy.schemaVersion,2);assert.equal(s.strategy.research.mode,'statistical_quant');assert(!s.strategy.graph);assert.equal(s.dataSource,'tushare');
await q.studio.initialize();await tick();
const poolCard=w.document.querySelector('[data-v2="universe"]');assert(poolCard,'actual rendered universe card');poolCard.click();await tick();
assert.equal(w.location.hash,'#quant/universe','reused collection button retains new route');assert(w.document.querySelector('.sq-shell'),'new workspace is retained');assert.equal(s.strategy.research.mode,'statistical_quant');
// Unknown or old snapshot fields remain visible and fail; explicit resolver output is projected.
s.strategy.universe.catalogSnapshot.unrecognizedProof=true;const rawDraft=structuredClone(s.strategy),loaded=w.AtlasQuantV4.normalizeStrategy(rawDraft);assert.equal(loaded.universe.catalogSnapshot.unrecognizedProof,true);loaded.universe.catalogSnapshot.asOf='changed';assert.notEqual(rawDraft.universe.catalogSnapshot.asOf,'changed','normalization does not alias saved nested metadata');assert(q.validateStrategy().some(x=>x.includes('unrecognizedProof')));w.document.querySelector('[data-v2="pool-resolve"]').click();await tick();assert.deepEqual(Object.keys(s.strategy.universe.catalogSnapshot).sort(),['asOf','hash','historicalMembershipVerified']);assert(!q.validateStrategy().some(x=>x.includes('快照')));
q.studio.flow.reset();delete s.strategy.universe.catalogSnapshot;delete s.strategy.universe.selection;delete s.strategy.universe.resolutionHash;delete s.strategy.universe.snapshotHash;q.render();
// Universe is explicit. A single asset is legitimate in the new architecture.
w.document.querySelector('#rq-subset-codes').value='600000.SH';w.document.querySelector('[data-v2="pool-manual"]').click();await tick();assert.deepEqual([...s.strategy.universe.symbols],['600000.SH']);assert(!('topN' in s.strategy.portfolio));assert(!('subsetPolicy' in s.strategy.universe),'direct explicit members do not manufacture a resolved-selection claim');
for(const name of ['state','target','model','validation','risk','execution','report']){await route(name);assert(w.document.querySelector('h1'));assert(w.document.querySelector('.sq-page-navigation'),'independent page navigation');assert.equal(w.document.activeElement.tagName,'H1','route focuses the new page heading');assert(w.document.title.endsWith('Atlas Quant'));}
await route('target');input('target.horizonSessions','8');input('research.observationDays','3');q.render();assert.equal(w.document.querySelector('[data-sq-config="target.horizonSessions"]').value,'8');assert.equal(s.research?.observationDays,undefined);assert.equal(s.strategy.research.observationDays,3);
w.document.querySelector('[data-sq="step"][data-id="model"]').click();await tick();assert.equal(w.location.hash,'#quant/model');input('model.trainWindow','252');input('model.refitDays','10');
await route('execution');input('portfolio.rebalanceDays','5');input('costs.slippageBps','0');input('costs.minCommission','0');
await route('report');assert.equal(q.validateStrategy().length,0);w.document.querySelector('[data-sq="save"]').click();await tick();assert.equal(saved.length,1);assert.equal(saved[0].target.horizonSessions,8);assert.equal(saved[0].model.trainWindow,252);assert.equal(saved[0].costs.slippageBps,0);assert.equal(saved[0].portfolio.rebalanceDays,5);assert.equal(q.workspace.ui.activeId,'experiment-test');
const draft=JSON.parse(w.localStorage.getItem('atlas-quant-statistical-draft-v2'));assert.equal(draft.experimentId,'experiment-test');assert.equal(draft.strategy.target.horizonSessions,8);
await route('target');w.document.querySelector('[data-sq="target-kind"][data-id="frozen_basket"]').click();await tick();assert(q.validateStrategy().some(x=>x.includes('恰好两个')));w.document.querySelector('[data-sq="step"][data-direction="next"]').click();await tick();assert.equal(w.location.hash,'#quant/target','incomplete target stops next locally');assert(w.document.querySelector('.sq-note.warning').textContent.includes('两条'));w.document.querySelector('[data-sq="target-kind"][data-id="asset_price"]').click();await tick();assert(!s.strategy.target.basket);
await route('universe');const manual=w.document.querySelector('#rq-subset-codes');manual.value='600';manual.dispatchEvent(new w.InputEvent('input',{bubbles:true}));q.render();assert.equal(w.document.querySelector('#rq-subset-codes').value,'600','partial explicit member input survives refresh');manual.value='600000.SH';manual.dispatchEvent(new w.InputEvent('input',{bubbles:true}));
await route('state');
const dragSource=w.document.querySelector('[data-v2-drag="factor:dom-momentum"]'),dropZone=w.document.querySelector('[data-v2-drop="recipe"]');assert(dragSource?.draggable,'available factor has native draggable');assert(!w.document.querySelector('[data-v2-drag="factor:dom-unavailable"]'),'unmapped factor cannot drag');
const store=new Map(),transfer={types:[],setData(type,value){store.set(type,value);this.types=[...store.keys()];},getData:type=>store.get(type)||''};
for(const [type,target] of [['dragstart',dragSource],['dragover',dropZone],['drop',dropZone],['dragend',dragSource]]){const event=new w.Event(type,{bubbles:true,cancelable:true});Object.defineProperty(event,'dataTransfer',{value:transfer});target.dispatchEvent(event);}await tick();assert(s.strategy.factors.some(x=>x.id==='dom-momentum'),'DataTransfer drag/drop adds actual definition');w.document.querySelector('[data-sq="remove-factor"][data-id="dom-momentum"]').click();await tick();
await q.workspace.applyModule({id:'test.factor',version:1,stage:'state',availability:{status:'ready'},patchSemantics:'append_factors',configPatch:{factors:[{id:'m20',expression:'returns(close,20)',direction:1,role:'predictor'}]}});assert.equal(s.strategy.factors.length,1);w.document.querySelector('[data-sq="remove-factor"]').click();await tick();assert.equal(s.strategy.factors.length,0);
// Re-rendering controls without IDs must retain the keyboard location.
await route('state');const add=w.document.querySelector('[data-v2="add-factor"][data-id="dom-momentum"]');add.focus();add.click();await tick();assert(s.strategy.factors.some(x=>x.id==='dom-momentum'),'native keyboard-operable button is equivalent to factor drag');
let role=w.document.querySelector('[data-sq-factor-role="dom-momentum"]');role.focus();role.value='predictor';role.dispatchEvent(new w.Event('change',{bubbles:true}));await tick();assert.equal(w.document.activeElement.dataset.sqFactorRole,'dom-momentum');
const moduleTab=w.document.querySelector('[data-sq="feature-tab"][data-id="modules"]');moduleTab.focus();moduleTab.click();await tick();assert.equal(w.document.activeElement.dataset.id,'modules');assert.equal(w.document.activeElement.getAttribute('aria-pressed'),'true');
// Returning to a long page keeps the previous expansion and scroll position.
const detail=[...w.document.querySelectorAll('details')].find(x=>x.dataset.sqDetails==='预处理与输入冗余');detail.open=true;w.scrollTo(0,740);await route('target');await route('state');assert.equal(w.scrollY,740);assert([...w.document.querySelectorAll('details')].find(x=>x.dataset.sqDetails==='预处理与输入冗余').open);
// Automatic desktop expansion must not become a false manual mobile preference.
viewport(true);assert(w.document.querySelector('#sq-summary').open);viewport(false);assert(!w.document.querySelector('#sq-summary').open);await route('target');assert(!w.document.querySelector('#sq-summary').open);w.document.querySelector('#sq-summary > summary').click();await tick();assert(w.document.querySelector('#sq-summary').open);viewport(false);await route('state');assert(w.document.querySelector('#sq-summary').open,'a genuine manual expansion is preserved');
// Skip navigation never becomes a route or resets an in-memory report.
const oldHash=w.location.hash;s.report={marker:'preserve'};w.document.querySelector('.skip-link').click();await tick();assert.equal(w.location.hash,oldHash);assert.equal(s.report.marker,'preserve');assert.equal(w.document.activeElement.id,'main-content');
// A failed catalog search exposes retry and hides stale results until successful retry.
failedPath='/statistical-quant/modules';await q.workspace.catalog.load('state');assert(w.document.querySelector('[data-sq="module-retry"]'));assert(!w.document.querySelector('.sq-module-grid'));failedPath='';w.document.querySelector('[data-sq="module-retry"]').click();await tick();assert(!q.workspace.catalog.state.error);
// Failed private report reads end the spinner; the ordinary button retries the same record.
failedPath='/runs/failed-readback';w.location.hash='#runs/failed-readback';await tick();assert(w.document.querySelector('main').textContent.includes('报告暂时无法读取'));assert(!w.document.querySelector('.loading-line'));failedPath='';w.document.querySelector('[data-action="refresh-report"]').click();await tick();assert.equal(s.job.status,'cancelled');assert.equal(s.reportError,'');assert.equal(w.document.querySelector('#sq-step-picker').value,'report');assert(w.document.querySelector('.sq-mode-switch').getAttribute('href').endsWith('/report'));
// Comparison UI creates a saved artifact and its route reads it back from the explicit API double.
await route('compare');const compareBoxes=[...w.document.querySelectorAll('[data-sq-compare]')];assert.equal(compareBoxes.length,2);assert(w.document.querySelector('[data-sq="compare-create"]').disabled);for(const id of ['forecast-test-a','forecast-test-b']){const checkbox=w.document.querySelector(`[data-sq-compare="${id}"]`);checkbox.checked=true;checkbox.dispatchEvent(new w.Event('change',{bubbles:true}));}w.document.querySelector('[data-sq="compare-create"]').click();await tick();assert.equal(comparisonPayload.kind,'forecast');assert.deepEqual(comparisonPayload.members,['forecast-test-a','forecast-test-b']);assert.equal(w.location.hash,'#quant/compare/comparison-test');assert(w.document.querySelector('main').textContent.includes('不能解释为控制其他条件后的增量'));q.workspace.ui.compare=null;await route('state');await route('compare/comparison-test');assert.equal(comparisonReads,1);assert(w.document.querySelector('a[download]').href.endsWith('/comparisons/comparison-test/download'));
// Readback of an execution comparison restores the editor kind before loading its choices.
savedComparison={...savedComparison,kind:'execution',name:'已保存执行比较'};q.workspace.ui.compare=null;q.workspace.ui.compareKind='forecast';await route('state');await route('compare/comparison-test');assert.equal(w.document.querySelector('#sq-compare-kind').value,'execution');assert.equal(q.workspace.ui.compareKind,'execution');savedComparison={...savedComparison,kind:'forecast',name:'预测证据比较'};q.workspace.ui.compareKind='forecast';
// The embedded Studio editor owns code-project actions, not a second legacy strategy header.
await route('studio/code');assert.equal(w.document.querySelectorAll('h1').length,1);assert(w.document.querySelector('[data-v2="save-code"]'));assert(!w.document.querySelector('.sq-content [data-action="save"]'));assert(!w.document.querySelector('.sq-content [data-action="run"]'));assert(!w.document.querySelector('#strategy-name'));
const releaseReview=hold('/code/review');w.document.querySelector('[data-v2="review-ai"]').click();await tick();const codeEditor=w.document.querySelector('#v2-code-editor');codeEditor.value='returns(close, 10)';codeEditor.dispatchEvent(new w.InputEvent('input',{bubbles:true}));releaseReview();await tick();assert(w.document.querySelector('main').textContent.includes('审阅来源与代码版本'));assert(w.document.querySelector('main').textContent.includes('API DOUBLE ONLY'));assert(w.document.querySelector('main').textContent.includes('d'.repeat(64)));assert(w.document.querySelector('main').textContent.includes('代码已在这次审阅后修改'));
await route('model');input('model.trainWindow','');assert.equal(s.strategy.model.trainWindow,null);q.render();assert.equal(w.document.querySelector('[data-sq-config="model.trainWindow"]').value,'');assert(q.validateStrategy().length>0);
// Slow initial requests cannot masquerade as an empty private workspace.
q.workspace.ui.compareLoaded=false;q.workspace.ui.comparisonHistoryLoaded=false;q.workspace.ui.compareChoices=[];q.workspace.ui.comparisons=[];q.workspace.ui.compareTotal=0;q.workspace.ui.comparisonHistoryTotal=0;q.workspace.ui.compare=null;
const releaseChoices=hold('/statistical-quant/forecasts?'),releaseHistory=hold('/statistical-quant/comparisons?');w.location.hash='#quant/compare';q.parseRoute();q.render();let firstFrame=w.document.querySelector('main').textContent;assert(firstFrame.includes('读取当前研究产物'));assert(firstFrame.includes('正在读取已保存比较'));assert(!firstFrame.includes('尚无可比较产物'));assert(!firstFrame.includes('尚未保存比较'));assert(!firstFrame.includes('共 0 项'));await tick();releaseChoices();await tick();assert(w.document.querySelector('[data-sq-compare]'));assert(w.document.querySelector('main').textContent.includes('正在读取已保存比较'),'history loads independently');releaseHistory();await tick();assert(w.document.querySelector('main').textContent.includes('预测证据比较'));
// A successful empty response is different from loading and from failure.
forecastFixtureOverride=[];historyFixtureOverride=[];w.document.querySelector('[data-sq="compare-refresh"]').click();await tick();assert(w.document.querySelector('main').textContent.includes('尚无可比较产物'));assert(w.document.querySelector('main').textContent.includes('尚未保存比较'));failedPath='/statistical-quant/forecasts?';w.document.querySelector('[data-sq="compare-refresh"]').click();await tick();assert(w.document.querySelector('main').textContent.includes('QA 网络中断'));assert(!w.document.querySelector('main').textContent.includes('尚无可比较产物'));failedPath='';
q.workspace.ui.experimentsLoaded=false;q.workspace.ui.experiments=[];q.workspace.ui.experimentTotal=0;const releaseResearches=hold('/statistical-quant/experiments?');w.location.hash='#quant/researches';q.parseRoute();q.render();firstFrame=w.document.querySelector('main').textContent;assert(firstFrame.includes('正在读取私有研究'));assert(!firstFrame.includes('还没有保存的统计研究'));assert(!firstFrame.includes('共 0 项'));await tick();releaseResearches();await tick();assert(w.document.querySelector('main').textContent.includes('还没有保存的统计研究'));
// A saved configuration is not evidence that no jobs exist; current latest forecast/execution comes from the list API.
q.workspace.ui.experimentsLoaded=true;q.workspace.ui.loading=false;q.workspace.ui.experiments=[{id:'not-run',name:'尚未运行研究',version:1,latestRun:null},{id:'finished',name:'已有执行研究',version:2,latestRun:{id:'execution-report',status:'completed',jobKind:'execution',experimentVersion:1}},{id:'old-server',name:'旧服务字段缺失',version:1}];q.render();assert(w.document.querySelector('a[href="#runs/execution-report"]').textContent.includes('已完成'));assert(w.document.querySelector('main').textContent.includes('独立执行 · 研究 v1'));assert(w.document.querySelector('main').textContent.includes('运行状态尚未返回'));assert(!w.document.querySelector('main').textContent.includes('配置已保存'));
// A delayed detail read cannot show a previous study or navigate the user back after they leave.
q.workspace.ui.viewedExperiment={experiment:{id:'older-detail',name:'不应闪现的旧研究'}};const releaseDetail=hold('/statistical-quant/experiments/fresh-detail');await route('experiment/fresh-detail');assert(w.document.querySelector('main').textContent.includes('正在读取这份研究'));assert(!w.document.querySelector('main').textContent.includes('不应闪现的旧研究'));await route('state');releaseDetail();await tick();assert.equal(w.location.hash,'#quant/state','late read must not force old route');await route('experiment/fresh-detail');assert(w.document.querySelector('main').textContent.includes('新研究详情'));
// Edits and switching drafts during a slow save cannot be overwritten by the older response.
s.strategy=w.AtlasQuantV4.defaultStrategy();s.strategy.universe.symbols=['600000.SH'];q.workspace.ui.activeId=null;q.workspace.ui.activeVersion=null;s.dirty=true;await route('target');let releaseSave=hold('/statistical-quant/experiments');w.document.querySelector('[data-sq="save"]').click();await tick();assert(s.saving);input('target.horizonSessions','9');releaseSave();await tick();assert.equal(saved.at(-1).target.horizonSessions,5,'request used its own submitted snapshot');assert.equal(s.strategy.target.horizonSessions,9,'later input remains in the current draft');assert(s.dirty,'later input stays explicitly unsaved');assert.equal(q.workspace.ui.activeVersion,1);
q.workspace.ui.activeId=null;q.workspace.ui.activeVersion=null;releaseSave=hold('/statistical-quant/experiments');w.document.querySelector('[data-sq="save"]').click();await tick();await route('researches');w.document.querySelector('[data-sq="new"]').click();await tick();const freshName=w.document.querySelector('#sq-research-name');freshName.value='切换后的新草稿';freshName.dispatchEvent(new w.InputEvent('input',{bubbles:true}));releaseSave();await tick();assert.equal(s.strategy.name,'切换后的新草稿');assert.equal(q.workspace.ui.activeId,null,'old save must not attach its ID to the new draft');assert.equal(s.strategy.target.horizonSessions,5);assert(s.dirty);
console.log(JSON.stringify({dom:'jsdom',cycle4FocusAndErrorRecovery:true,comparisonCreateAndReadback:true,delayedInitialLists:true,pendingSavePreservesEdits:true,independentPages:8,inputEvents:true,saveReadback:true,explicitSingleAsset:true,testsUseApiDoubles:true,browserVisualAcceptance:false}));dom.window.close();
