import {ApiError} from './errors.mjs';

const NOW=()=>new Date().toISOString();
const random=()=>crypto.randomUUID();
const json=(v,status=200,headers={})=>new Response(JSON.stringify(v),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store','x-content-type-options':'nosniff',...headers}});
const parse=(v,fallback=null)=>{try{return JSON.parse(v);}catch{return fallback;}};
const safeError=e=>e instanceof ApiError?e:new ApiError('SERVER_ERROR','服务暂时无法完成请求，请稍后重试。',500);
async function sha(s){return [...new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s)))].map(x=>x.toString(16).padStart(2,'0')).join('');}
async function body(req,max=100000){const len=Number(req.headers.get('content-length')||0);if(len>max)throw new ApiError('TOO_LARGE','请求超过大小限制',413);let text='',bytes=0;const reader=req.body?.getReader(),decoder=new TextDecoder('utf-8',{fatal:true});try{if(reader)while(true){const {done,value}=await reader.read();if(done)break;bytes+=value.byteLength;if(bytes>max){await reader.cancel();throw new ApiError('TOO_LARGE','请求超过大小限制',413);}text+=decoder.decode(value,{stream:true});}text+=decoder.decode();const parsed=JSON.parse(text);if(!parsed||typeof parsed!=='object'||Array.isArray(parsed))throw new ApiError('INVALID_INPUT','请求正文必须为对象');return parsed;}catch(e){if(e instanceof ApiError)throw e;throw new ApiError('INVALID_JSON','请求必须为 UTF-8 JSON');}finally{reader?.releaseLock();}}
function checkOrigin(req){const origin=req.headers.get('origin');if(origin&&origin!==new URL(req.url).origin)throw new ApiError('FORBIDDEN_ORIGIN','仅允许本站发起此操作',403);if(req.headers.get('sec-fetch-site')==='cross-site')throw new ApiError('FORBIDDEN_ORIGIN','跨站请求已拒绝',403);if(!['GET','HEAD'].includes(req.method)&&!req.headers.get('content-type')?.startsWith('application/json'))throw new ApiError('CONTENT_TYPE','请使用 JSON 请求',415);}
async function rate(env,key,limit,seconds){const bucket=Math.floor(Date.now()/(seconds*1000));const k=`${key}:${bucket}`;const r=await env.DB.prepare('INSERT INTO rate_buckets(key,count,expires_at) VALUES(?,1,?) ON CONFLICT(key) DO UPDATE SET count=count+1 RETURNING count').bind(k,new Date((bucket+2)*seconds*1000).toISOString()).first();if(r.count>limit)throw new ApiError('RATE_LIMITED','请求较多，请稍后再试。',429);}
async function audit(env,owner,action,id,detail={}){await env.DB.prepare('INSERT INTO audit(id,owner,action,entity_id,detail,created_at) VALUES(?,?,?,?,?,?)').bind(random(),owner,action,id,JSON.stringify(detail),NOW()).run();}
function cookie(req){const m=/(?:^|;\s*)aq_session=([a-f0-9-]{36}\.[a-f0-9-]{36})(?:;|$)/.exec(req.headers.get('cookie')||'');return m?.[1];}
async function workspace(req,env,create=false){const token=cookie(req);if(token){const w=await env.DB.prepare('SELECT id,name,created_at FROM workspaces WHERE token_hash=?').bind(await sha(token)).first();if(w)return {workspace:w};}if(!create)throw new ApiError('SESSION_REQUIRED','请刷新页面以建立工作区',401);await rate(env,'session:'+await sha(req.headers.get('cf-connecting-ip')||'local'),40,3600);const secret=random()+'.'+random(),id=random(),name='我的研究工作区';await env.DB.prepare('INSERT INTO workspaces(id,token_hash,name,created_at) VALUES(?,?,?,?)').bind(id,await sha(secret),name,NOW()).run();return {workspace:{id,name},cookie:`aq_session=${secret}; HttpOnly; Secure; SameSite=Strict; Path=/quant/; Max-Age=31536000`};}
async function runnerState(env){const r=await env.DB.prepare("SELECT value,updated_at FROM meta WHERE key='runner'").first();const v=parse(r?.value,{});return {online:!!r&&Date.now()-Date.parse(r.updated_at)<120000,lastSeen:r?.updated_at||null,state:v.state||'offline',engineVersion:v.engineVersion||null};}
function strategyItem(r){return {id:r.id,name:r.name,version:r.version,strategy:parse(r.spec),createdAt:r.created_at,updatedAt:r.updated_at};}
function jobItem(r){return {id:r.id,name:r.name,status:r.status,dataSource:r.data_source,createdAt:r.created_at,updatedAt:r.updated_at,summary:parse(r.summary),error:parse(r.error),strategy:parse(r.spec)};}
function factorItem(r){return {id:r.id,name:r.name,description:r.description,expression:r.expression,direction:r.direction,category:r.category,author:r.author,license:r.license,sourceUrl:r.source_url,forkOf:r.fork_of,version:r.version,status:r.status,...parse(r.metadata,{}),createdAt:r.created_at};}

export {NOW, random, json, parse, safeError, sha, body, checkOrigin, rate, audit, cookie, workspace, runnerState, strategyItem, jobItem, factorItem};
