import {marketResearchApi} from './market-preparation/research-reader.mjs';
import {admitMarketResearch} from './market-preparation/research.mjs';
import {recordRunnerCapabilities} from './runner-capabilities.mjs';
import {marketRunnerApi} from './market-preparation/runner-api.mjs';
import {marketPreparationApi} from './market-preparation/api.mjs';
import {readScope,bindWholeScope} from './market-preparation/scope.mjs';
import {financialBundleRunnerApi} from './financial-bundles/runner-api.mjs';
import {researchDatasetApi} from './datasets/research-reader.mjs';
import {assertRunDataset,admitDatasetResearch,financialFields,researchEnabled,supportsFinancialDatasets} from './datasets/research.mjs';
import {datasetApi} from './datasets/api.mjs';
import {datasetRunnerApi} from './datasets/runner-api.mjs';
import {acquisitionApi} from './financial-acquisition/api.mjs';
import {acquisitionRunnerApi} from './financial-acquisition/runner-api.mjs';
import {financialApi} from './financial/api.mjs';
import {financialRunnerApi} from './financial/runner-api.mjs';
import {ownedStageForRun,parsedStage} from './bundles/storage.mjs';
import {streamDocumentResponse} from './bundles/user-api.mjs';
import {cleanupAbandonedBundles} from './bundles/retention.mjs';
import {completeBundle} from './bundles/publication.mjs';
import {bundleRunnerApi} from './bundles/runner-api.mjs';
import {bundleUserApi} from './bundles/user-api.mjs';
import {modelFunctionsApi} from './model-functions/api.mjs';
import {claimRunnerJob} from './runner-claims.mjs';
import {statisticalCatalog} from './statistical-quant/modules.mjs';
import {validateStatisticalQuant,validateStoredStatisticalQuant} from './statistical-quant/validation.mjs';
import {statisticalQuantPrivate, createExperiment} from './statistical-quant/api.mjs';
import {statisticalRunnerApi} from './statistical-quant/runner-api.mjs';
import {validateForecastCompletion, persistForecastCompletion, cleanupFailedForecastSnapshots} from './statistical-quant/persistence.mjs';
import {NOW, random, json, parse, safeError, sha, body, checkOrigin, rate, audit, workspace, runnerState, strategyItem, jobItem, factorItem} from './runtime.mjs';
import {studioPublic, studioPrivate, resolveUniverseRules, fieldRecipe, fieldView} from './studio.mjs';
import {ApiError,validateStrategy,validateFactor,validateDataset} from './validation.mjs';
// Build injects WEB_ASSETS, CATALOG, BUILD_ID without credentials.
function validateCurrentStrategy(input) {
  return input?.schemaVersion===2||input?.research?.mode==='statistical_quant'
    ? validateStatisticalQuant(input) : validateStrategy(input);
}
async function builtinAndCommunity(env){const rows=await env.DB.prepare("SELECT * FROM factors WHERE status='published' ORDER BY created_at DESC LIMIT 300").all();return [...CATALOG.factors.map(f=>({...f,author:'Atlas Quant',license:'Apache-2.0',version:1,status:'builtin'})),...rows.results.map(factorItem)];}
async function findFactor(env,id){if(id.startsWith('field_')){const [,transform,alias]=/^field_(value|rank|zscore)_(.+)$/.exec(id)||[];if(['value','rank','zscore'].includes(transform)){const row=await env.DB.prepare('SELECT * FROM data_fields WHERE alias=? AND numeric_eligible=1').bind(alias).first();if(row)return fieldRecipe(fieldView(row),transform);}}const builtin=CATALOG.factors.find(f=>f.id===id);if(builtin)return {...builtin,author:'Atlas Quant',license:'Apache-2.0',version:1,status:'builtin'};const row=await env.DB.prepare("SELECT * FROM factors WHERE id=? AND status='published'").bind(id).first();return row?factorItem(row):null;}
function capability(env){return {demo:true,upload:true,tushareHosted:env.TUSHARE_PUBLIC_AUTHORIZED==='true',localTushare:true,aiReview:!!env.AI,pythonBrowser:true,studio:true};}
async function authorizeRunner(req,env){const value=req.headers.get('authorization')||'';if(!env.RUNNER_SECRET||await sha(value)!==await sha('Bearer '+env.RUNNER_SECRET))throw new ApiError('UNAUTHORIZED','需要计算服务凭据',401);}
async function enqueue(env,owner,input,internal=false,researchLink=null) {
  const frozenScope=input.universeScopeRef?await readScope(env,owner,input.universeScopeRef):null;
  let strategy=frozenScope?validateStatisticalQuant(bindWholeScope(input.strategy,frozenScope.scope),{scopeSymbolLimit:10000}):validateCurrentStrategy(input.strategy);
  if(frozenScope&&strategy.universe.symbols.length>50&&input.dataSource!=='ready_market')throw new ApiError('WHOLE_UNIVERSE_PROFILE_NOT_READY','完整集合已冻结；大池研究需要独立准备的市场数据及匹配计算能力，当前入口不会截断为50只',409);
  if(!frozenScope&&strategy.universe.selection&&researchLink?.kind!=='execution') {
    const resolved=await resolveUniverseRules(env,strategy.universe.selection),u=strategy.universe;
    if(resolved.resolutionHash!==u.resolutionHash||resolved.snapshotHash!==u.snapshotHash) throw new ApiError('UNIVERSE_CHANGED','股票池规则或目录版本已变化，请重新解析并确认成员。',409);
    const members=new Set(resolved.symbols);
    if(u.symbols.some(x=>!members.has(x))||(u.subsetPolicy==='all'&&u.symbols.length!==members.size)) throw new ApiError('UNIVERSE_SUBSET_MISMATCH','运行成员与已解析股票池不一致，请明确选择子集。');
    const snapshot=resolved.catalogSnapshot;
    u.catalogSnapshot={hash:snapshot.hash,asOf:snapshot.asOf??null,historicalMembershipVerified:false};
    // Trusted resolver metadata must pass the same execution contract after binding.
    strategy=validateCurrentStrategy(strategy);
  }
  const ds=input.dataSource,replay=researchLink?.kind==='execution';
  if(!(['demo','upload','tushare','ready_dataset','ready_market'].includes(ds)||(replay&&ds==='replay'))) throw new ApiError('INVALID_SOURCE','请选择数据来源');
  if(ds==='tushare'&&!internal&&env.TUSHARE_PUBLIC_AUTHORIZED!=='true') throw new ApiError('DATA_AUTHORIZATION_REQUIRED','托管Tushare数据接入尚未开放，请使用已授权本地或上传来源。',403);
  if(ds!=='ready_dataset'&&(input.datasetRef!==undefined||(input.admissionProfile!==undefined&&ds!=='ready_market')||financialFields(strategy).length)) throw new ApiError('DATASET_REQUIRED','已登记财务状态只能使用已冻结数据集研究入口');
  if(ds==='ready_dataset'&&(internal||replay)) throw new ApiError('DATASET_RESEARCH_PROFILE','财务数据集仅支持明确的工作区预测实验');
  if(ds!=='ready_market'&&input.marketDatasetRef!==undefined)throw new ApiError('MARKET_RESEARCH_SOURCE','市场来源引用必须使用 ready_market');
  if(ds==='ready_market'&&(internal||replay||!frozenScope))throw new ApiError('MARKET_RESEARCH_PROFILE','市场完整池仅支持绑定范围的工作区预测研究');
  const marketAdmitted=ds==='ready_market'?await admitMarketResearch(env,owner,strategy,input):null;
  const admitted=ds==='ready_dataset'?await admitDatasetResearch(env,owner,strategy,input):null;
  await rate(env,'runs:'+owner,20,86400);
  const dataset=ds==='upload'?validateDataset(input.dataset,strategy):null;
  const active=await env.DB.prepare("SELECT count(*) n FROM jobs WHERE owner=? AND status IN ('queued','running')").bind(owner).first();
  if(active.n) throw new ApiError('JOB_ACTIVE','工作区已有实验运行中，请等待或取消。',409);
  if(strategy.schemaVersion===2&&!researchLink) {
    const experiment=await createExperiment(env,owner,strategy,null,admitted?input:null,input.universeScopeRef??null,marketAdmitted?input:null);
    researchLink={experimentId:experiment.id,experimentVersion:experiment.version,kind:'forecast'};
  }
  const id=random(),time=NOW(),datasetKey=dataset?`datasets/${owner}/${id}.json`:null;
  if(datasetKey) await env.ARTIFACTS.put(datasetKey,JSON.stringify(dataset),{httpMetadata:{contentType:'application/json'}});
  const datasetGuard=admitted?` AND EXISTS(SELECT 1 FROM quant_research_datasets d JOIN quant_dataset_stages s ON s.id=d.stage_id AND s.owner=d.owner WHERE d.id=? AND d.owner=? AND d.dataset_root=? AND d.status='ready' AND s.status='committed') AND NOT EXISTS(SELECT 1 FROM json_each(?) x WHERE NOT EXISTS(SELECT 1 FROM financial_registry_entries r WHERE r.id=json_extract(x.value,'$.ref') AND r.owner=? AND r.status='active' AND r.sha256=json_extract(x.value,'$.sha256') AND r.byte_length=json_extract(x.value,'$.byteLength') AND r.kind=json_extract(x.value,'$.kind')))` : '';
  const marketGuard=marketAdmitted?` AND EXISTS(SELECT 1 FROM quant_market_datasets d JOIN quant_market_publications p ON p.job_id=d.job_id AND p.owner=d.owner WHERE d.id=? AND d.owner=? AND d.dataset_root=? AND d.status='ready' AND p.status='committed' AND p.manifest_hash=d.dataset_root)`:'';
  const statements=[env.DB.prepare("INSERT INTO jobs(id,owner,name,status,data_source,spec,dataset_key,created_at,updated_at) SELECT ?,?,?, 'queued',?,?,?,?,? WHERE NOT EXISTS(SELECT 1 FROM jobs WHERE owner=? AND status IN ('queued','running')) AND (SELECT count(*) FROM jobs WHERE status IN ('queued','running'))<30"+datasetGuard+marketGuard).bind(id,owner,strategy.name,ds,JSON.stringify(strategy),datasetKey,time,time,owner,...(admitted?[admitted.dataset.id,owner,admitted.dataset.dataset_root,JSON.stringify(admitted.plan.sources.registry),owner]:[]),...(marketAdmitted?[marketAdmitted.dataset.id,owner,marketAdmitted.dataset.dataset_root]:[]))];
  if(frozenScope) statements.push(env.DB.prepare('INSERT INTO quant_run_scopes(job_id,owner,scope_id,scope_root,created_at) SELECT ?,?,?,?,? WHERE EXISTS(SELECT 1 FROM jobs WHERE id=?)').bind(id,owner,frozenScope.row.id,frozenScope.row.scope_root,time,id));
  if(admitted) statements.push(env.DB.prepare('INSERT INTO quant_run_datasets(job_id,owner,dataset_id,dataset_root,profile,admission,created_at) SELECT ?,?,?,?,?,?,? WHERE EXISTS(SELECT 1 FROM jobs WHERE id=?)').bind(id,owner,admitted.dataset.id,admitted.dataset.dataset_root,admitted.admissionProfile,JSON.stringify({strategyHash:admitted.strategyHash,sourceEvidence:admitted.sourceEvidence}),time,id));
  if(marketAdmitted) statements.push(env.DB.prepare('INSERT INTO quant_run_market_datasets(job_id,owner,dataset_id,dataset_root,profile,created_at) SELECT ?,?,?,?,?,? WHERE EXISTS(SELECT 1 FROM jobs WHERE id=?)').bind(id,owner,marketAdmitted.dataset.id,marketAdmitted.dataset.dataset_root,marketAdmitted.admissionProfile,time,id));
  if(researchLink) {
    statements.push(env.DB.prepare('INSERT INTO quant_runs(job_id,owner,experiment_id,experiment_version,kind,source_forecast_id,created_at) SELECT ?,?,?,?,?,?,? WHERE EXISTS(SELECT 1 FROM jobs WHERE id=?)').bind(id,owner,researchLink.experimentId,researchLink.experimentVersion,researchLink.kind,researchLink.sourceForecastId??null,time,id));
    if(replay) statements.push(env.DB.prepare('INSERT INTO quant_executions(id,owner,experiment_id,forecast_artifact_id,spec,created_at) SELECT ?,?,?,?,?,? WHERE EXISTS(SELECT 1 FROM jobs WHERE id=?)').bind(id,owner,researchLink.experimentId,researchLink.sourceForecastId,JSON.stringify({execution:strategy.execution,portfolio:strategy.portfolio,costs:strategy.costs}),time,id));
  }
  const results=await env.DB.batch(statements);
  if(!results[0].meta.changes) {
    if(datasetKey) await env.ARTIFACTS.delete(datasetKey);
    throw new ApiError('QUEUE_BUSY','工作区已有实验或全局队列已满，请稍后重试。',409);
  }
  await audit(env,owner,'run.created',id,{dataSource:ds,strategyHash:await sha(JSON.stringify(strategy)),jobKind:researchLink?.kind??'legacy'});
  return {id,status:'queued',name:strategy.name,dataSource:ds,createdAt:time,...(researchLink?{experimentId:researchLink.experimentId,jobKind:researchLink.kind}: {})};
}
async function runnerApi(req,env,path){await authorizeRunner(req,env);const marketReadResponse=await marketResearchApi(req,env,path);if(marketReadResponse)return marketReadResponse;const marketResponse=await marketRunnerApi(req,env,path);if(marketResponse)return marketResponse;const datasetReadResponse=await researchDatasetApi(req,env,path);if(datasetReadResponse)return datasetReadResponse;const datasetResponse=await datasetRunnerApi(req,env,path);if(datasetResponse)return datasetResponse;const acquisitionResponse=await acquisitionRunnerApi(req,env,path);if(acquisitionResponse)return acquisitionResponse;const financialResponse=await financialRunnerApi(req,env,path);if(financialResponse)return financialResponse;const financialBundleResponse=await financialBundleRunnerApi(req,env,path,{assertRunDataset});if(financialBundleResponse)return financialBundleResponse;const bundleResponse=await bundleRunnerApi(req,env,path);if(bundleResponse)return bundleResponse;if(req.method!=='POST')throw new ApiError('METHOD','需要 POST',405);const researchResponse=await statisticalRunnerApi(req,env,path);if(researchResponse)return researchResponse;const input=await body(req,path==='/runner/complete'?26*1024*1024:100000);const now=NOW();
 if(path==='/runner/heartbeat'||path==='/runner/claim')await recordRunnerCapabilities(env,input,now,path==='/runner/claim');
 if(path==='/runner/heartbeat'){if(input.id&&input.leaseToken){const updated=await env.DB.prepare("UPDATE jobs SET lease_until=?,updated_at=? WHERE id=? AND lease_token=? AND status='running'").bind(new Date(Date.now()+20*60000).toISOString(),now,input.id,input.leaseToken).run();return json({ok:true,leaseValid:!!updated.meta.changes,cancelled:!updated.meta.changes});}return json({ok:true});}
 if(path==='/runner/enqueue'){const owner='operator';return json({job:await enqueue(env,owner,input,true)},201);}
 if(path==='/runner/inspect'){const r=await env.DB.prepare('SELECT * FROM jobs WHERE id=?').bind(String(input.id||'')).first();if(!r)throw new ApiError('NOT_FOUND','实验不存在',404);const stage=await ownedStageForRun(env,r.owner,r.id);if(stage)return streamDocumentResponse(env,stage,await parsedStage(stage),'report',{prefix:JSON.stringify({job:jobItem(r)}).slice(0,-1)+',\"result\":',suffix:'}'});const obj=r.result_key?await env.ARTIFACTS.get(r.result_key):null;return json({job:jobItem(r),result:obj?await obj.json():null});}
 if(path==='/runner/claim')return json(await claimRunnerJob(env,input,now));
 if(path==='/runner/complete'){
 if(Object.hasOwn(input,'bundleId')||Object.hasOwn(input,'stageId')){if(input.result!==undefined||input.error!==undefined||!input.bundleId||!input.stageId)throw new ApiError('INVALID_COMPLETION','分片完成不能同时提交报告或错误');return json(await completeBundle(env,input));}
 const r=await env.DB.prepare("SELECT * FROM jobs WHERE id=? AND lease_token=? AND status IN ('running','completed','failed','cancelled')").bind(String(input.id||''),String(input.leaseToken||'')).first();if(!r)throw new ApiError('STALE_LEASE','实验已取消或运行租约失效',409);if(r.status!=='running'){if(r.status==='cancelled'||(r.status==='failed'&&parse(r.error)?.code==='RUNNER_INTERRUPTED'))return json({ok:true,status:r.status,ignored:true});if(r.status==='completed'&&input.result){const previous=await env.ARTIFACTS.get(r.result_key);if(previous&&await sha(await previous.text())===await sha(JSON.stringify(input.result))){const prepared=await validateForecastCompletion(env,r,input.result);await persistForecastCompletion(env,r,input.result,prepared);return json({ok:true,status:'completed',idempotent:true});}}if(r.status==='failed'&&input.error&&parse(r.error)?.code===String(input.error.code||'COMPUTE_FAILED')&&parse(r.error)?.message===String(input.error.message||'实验未完成').slice(0,700))return json({ok:true,status:'failed',idempotent:true});throw new ApiError('COMPLETION_CONFLICT','此实验已有不同的终态',409);}if(input.error){const error={code:String(input.error.code||'COMPUTE_FAILED').slice(0,80),message:String(input.error.message||'实验未完成').slice(0,700)};await env.DB.prepare("UPDATE jobs SET status='failed',error=?,updated_at=? WHERE id=? AND lease_token=? AND status='running'").bind(JSON.stringify(error),now,r.id,r.lease_token).run();return json({ok:true,status:'failed'});}
 if(r.data_source==='ready_market')throw new ApiError('MARKET_TRANSPORT_REQUIRED','完整市场研究必须使用来源绑定的分片协议',409);
 if(r.data_source==='ready_dataset')throw new ApiError('FINANCIAL_TRANSPORT_REQUIRED','财务研究必须使用独立 financial_bundle 完成协议',409);
 const result=input.result;const prepared=result?await validateForecastCompletion(env,r,result):null;if(!result||(!prepared&&!result.metrics)||!Array.isArray(result.equity)||!result.selection||!result.provenance)throw new ApiError('INVALID_RESULT','研究报告缺少必需的计算证据');const resultText=JSON.stringify(result);if(new TextEncoder().encode(resultText).byteLength>24*1024*1024)throw new ApiError('RESULT_TOO_LARGE','研究报告超过 24 MiB',413);if(/"(?:token|serviceToken|api_key|password|authorization)"\s*:/i.test(resultText))throw new ApiError('SENSITIVE_RESULT','报告包含不应公开的凭据字段');const resultHash=await sha(resultText);const resultKey=`results/${r.owner}/${r.id}/${resultHash}.json`;await env.ARTIFACTS.put(resultKey,resultText,{httpMetadata:{contentType:'application/json'}});const summary={...result.metrics,winner:result.selection.winner,evidenceStatus:result.selection.evidenceStatus,engineVersion:result.engineVersion};const updated=await env.DB.prepare("UPDATE jobs SET status='completed',result_key=?,summary=?,updated_at=? WHERE id=? AND lease_token=? AND status='running'").bind(resultKey,JSON.stringify(summary),now,r.id,r.lease_token).run();if(!updated.meta.changes){const current=await env.DB.prepare('SELECT status,result_key,error FROM jobs WHERE id=?').bind(r.id).first();if(current?.status==='completed'&&current.result_key===resultKey){await persistForecastCompletion(env,r,result,prepared);return json({ok:true,status:'completed',idempotent:true});}if(current?.result_key!==resultKey)await env.ARTIFACTS.delete(resultKey);if(current?.status==='cancelled'||(current?.status==='failed'&&parse(current.error)?.code==='RUNNER_INTERRUPTED'))return json({ok:true,status:current.status,ignored:true});throw new ApiError('COMPLETION_CONFLICT','此实验已有不同的终态',409);}await persistForecastCompletion(env,r,result,prepared);if(r.dataset_key)await env.ARTIFACTS.delete(r.dataset_key);await audit(env,r.owner,'run.completed',r.id,{resultHash:await sha(resultText)});return json({ok:true,status:'completed'});
 }
 throw new ApiError('NOT_FOUND','接口不存在',404);
}
async function api(req,env,path){checkOrigin(req);if(path.startsWith('/runner/'))return runnerApi(req,env,path);
 const quantCatalog=statisticalCatalog(req,path,CATALOG,RESEARCH_PRESETS);if(quantCatalog)return quantCatalog;
 const publicStudio=await studioPublic(req,env,path);if(publicStudio)return publicStudio;
 if(path==='/health')return json({ok:true,service:'Atlas Quant',version:BUILD_ID,runner:await runnerState(env),capabilities:capability(env)});
 if(path==='/catalog'&&req.method==='GET')return json({...CATALOG,factors:await builtinAndCommunity(env),dataSources:[{id:'demo',name:'合成数据教程',available:true,description:'完全合成的教学数据，不代表任何证券实际表现'},{id:'upload',name:'导入个人数据',available:true},{id:'tushare',name:'Tushare',available:capability(env).tushareHosted,localAdapter:true}],limits:{maxSymbols:50,minSymbols:3,maxFactors:32,maxRows:110000,maxDatasetBytes:24*1024*1024,maxActiveRuns:1},sourceUrl:env.SOURCE_URL||'/quant/source.zip'});
 if(path==='/factors'&&req.method==='GET')return json({items:await builtinAndCommunity(env)});
 if(path.startsWith('/factors/')&&req.method==='GET'){const id=path.split('/')[2],item=await findFactor(env,id);if(!item)throw new ApiError('NOT_FOUND','因子不存在',404);return json({item});}
 if(path==='/session'&&req.method==='GET'){const w=await workspace(req,env,true);return json({workspace:w.workspace,runner:await runnerState(env),capabilities:capability(env),sourceUrl:env.SOURCE_URL||'/quant/source.zip'},200,w.cookie?{'set-cookie':w.cookie}:{});}
 const {workspace:w}=await workspace(req,env);const owner=w.id;await rate(env,'requests:'+owner,180,60);const marketResponse=await marketPreparationApi(req,env,path,owner);if(marketResponse)return marketResponse;const datasetResponse=await datasetApi(req,env,path,owner);if(datasetResponse)return datasetResponse;const acquisitionResponse=await acquisitionApi(req,env,path,owner);if(acquisitionResponse)return acquisitionResponse;const financialResponse=await financialApi(req,env,path,owner);if(financialResponse)return financialResponse;const functionResponse=await modelFunctionsApi(req,env,path,owner);if(functionResponse)return functionResponse;const bundleResponse=await bundleUserApi(req,env,path,owner);if(bundleResponse)return bundleResponse;const researchResponse=await statisticalQuantPrivate(req,env,path,owner,{enqueue});if(researchResponse)return researchResponse;const privateStudio=await studioPrivate(req,env,path,owner);if(privateStudio)return privateStudio;
 if(path==='/strategies'&&req.method==='GET'){const rows=await env.DB.prepare('SELECT * FROM strategies WHERE owner=? ORDER BY updated_at DESC LIMIT 200').bind(owner).all();return json({items:rows.results.map(strategyItem)});}
 if(path==='/strategies'&&req.method==='POST'){const {strategy}=await body(req,200000);const s=validateCurrentStrategy(strategy);const n=await env.DB.prepare('SELECT count(*) n FROM strategies WHERE owner=?').bind(owner).first();if(n.n>=200)throw new ApiError('LIMIT','最多保存 200 个策略');const id=random(),time=NOW(),spec=JSON.stringify(s);await env.DB.batch([env.DB.prepare('INSERT INTO strategies(id,owner,name,spec,created_at,updated_at) VALUES(?,?,?,?,?,?)').bind(id,owner,s.name,spec,time,time),env.DB.prepare('INSERT INTO strategy_versions(strategy_id,version,spec,created_at) VALUES(?,1,?,?)').bind(id,spec,time)]);return json({item:{id,name:s.name,strategy:s,version:1,createdAt:time,updatedAt:time}},201);}
 if(path.startsWith('/strategies/')){const id=path.split('/')[2];const row=await env.DB.prepare('SELECT * FROM strategies WHERE id=? AND owner=?').bind(id,owner).first();if(!row)throw new ApiError('NOT_FOUND','策略不存在',404);if(req.method==='GET')return json({item:strategyItem(row)});if(req.method==='DELETE'){await env.DB.batch([env.DB.prepare('DELETE FROM strategy_versions WHERE strategy_id=?').bind(id),env.DB.prepare('DELETE FROM strategies WHERE id=? AND owner=?').bind(id,owner)]);return json({ok:true});}if(req.method==='PUT'){const {strategy,version}=await body(req,200000);if(version!==row.version)throw new ApiError('REVISION_CONFLICT','另一窗口已更新策略，请重新载入后再修改。',409);const s=validateCurrentStrategy(strategy),time=NOW(),spec=JSON.stringify(s);const r=await env.DB.prepare('UPDATE strategies SET name=?,spec=?,version=version+1,updated_at=? WHERE id=? AND owner=? AND version=? RETURNING *').bind(s.name,spec,time,id,owner,version).first();if(!r)throw new ApiError('REVISION_CONFLICT','版本冲突，请重新载入',409);await env.DB.prepare('INSERT OR IGNORE INTO strategy_versions(strategy_id,version,spec,created_at) VALUES(?,?,?,?)').bind(id,r.version,spec,time).run();return json({item:strategyItem(r)});}}
 if(path==='/runs'&&req.method==='GET'){const rows=await env.DB.prepare('SELECT * FROM jobs WHERE owner=? ORDER BY created_at DESC LIMIT 100').bind(owner).all();return json({items:rows.results.map(jobItem)});}
 if(path==='/runs'&&req.method==='POST'){const input=await body(req,26*1024*1024);return json({job:await enqueue(env,owner,input)},202);}
 if(path.startsWith('/runs/')){const [,,id,action]=path.split('/');const r=await env.DB.prepare('SELECT * FROM jobs WHERE id=? AND owner=?').bind(id,owner).first();if(!r)throw new ApiError('NOT_FOUND','实验不存在',404);if(action==='cancel'&&req.method==='POST'){const x=await env.DB.prepare("UPDATE jobs SET status='cancelled',updated_at=? WHERE id=? AND owner=? AND status IN ('queued','running')").bind(NOW(),id,owner).run();if(r.dataset_key&&x.meta.changes)await env.ARTIFACTS.delete(r.dataset_key);return json({ok:true,status:x.meta.changes?'cancelled':r.status});}if(req.method==='GET'){const obj=r.result_key?await env.ARTIFACTS.get(r.result_key):null;const result=obj?await obj.json():null;return json({job:jobItem(r),result},200,action==='export'?{'content-disposition':`attachment; filename="atlas-quant-${id}.json"`}:{});}}
 if(path==='/factors'&&req.method==='POST'){await rate(env,'factor:'+owner,10,86400);const f=validateFactor(await body(req,12000));if(f.forkOf&&!await findFactor(env,f.forkOf))throw new ApiError('INVALID_FORK','原始因子不存在');const id='community_'+random(),time=NOW();await env.DB.prepare("INSERT INTO factors(id,owner,name,description,expression,direction,category,author,license,source_url,fork_of,status,metadata,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,'published',?,?)").bind(id,owner,f.name,f.description,f.expression,f.direction,f.category,f.author,f.license,f.sourceUrl,f.forkOf,JSON.stringify({...f.metadata,reviewStatus:'community_unreviewed'}),time).run();await audit(env,owner,'factor.published',id,{expressionHash:await sha(f.expression)});return json({item:{id,...f,status:'published',reviewStatus:'community_unreviewed',version:1,createdAt:time}},201);}
 if(path.startsWith('/factors/')&&req.method==='DELETE'){const id=path.split('/')[2];const r=await env.DB.prepare("UPDATE factors SET status='withdrawn' WHERE id=? AND owner=?").bind(id,owner).run();if(!r.meta.changes)throw new ApiError('NOT_FOUND','找不到你发布的因子',404);return json({ok:true});}
 throw new ApiError('NOT_FOUND','接口不存在',404);
}
const CSP="default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; font-src 'self'; connect-src 'self'; object-src 'none'; base-uri 'self'; frame-ancestors 'none'; frame-src 'self'; worker-src 'self'; form-action 'self'";
export default {
 async fetch(req,env,ctx){const url=new URL(req.url);try{
 if(url.pathname==='/quant')return Response.redirect(url.origin+'/quant/'+url.search,308);
 if(url.pathname.startsWith('/quant/api/'))return await api(req,env,url.pathname.slice('/quant/api'.length).replace(/\/$/,'')||'/');
 if(!['GET','HEAD'].includes(req.method))return json({error:{code:'METHOD',message:'方法不支持'}},405);
 if(url.pathname==='/quant/source.zip'){const obj=await env.ARTIFACTS.get('public/source.zip');if(!obj)return json({error:{code:'NOT_READY',message:'源码包正在准备'}},503);return new Response(req.method==='HEAD'?null:obj.body,{headers:{'content-type':'application/zip','content-disposition':'attachment; filename="atlas-quant-source.zip"','cache-control':'public,max-age=300'}});}
 const path=url.pathname.replace(/^\/quant\/?/,'');const sandboxAsset=['python-sandbox.html','python-sandbox.js','python-worker.js'].includes(path);const sandboxCsp="default-src 'none'; script-src 'self' https://cdn.jsdelivr.net 'wasm-unsafe-eval' blob:; connect-src 'self' https://cdn.jsdelivr.net; worker-src blob:; frame-ancestors 'self'; style-src 'unsafe-inline'; object-src 'none'; base-uri 'none'";const asset=WEB_ASSETS[path||'index.html']||(path.includes('.')?null:WEB_ASSETS['index.html']);if(!asset)return new Response('Not found',{status:404});return new Response(req.method==='HEAD'?null:asset.encoding==='base64'?Uint8Array.from(atob(asset.body),c=>c.charCodeAt(0)):asset.body,{headers:{'content-type':asset.type,'cache-control':/\.[cm]?js$/.test(path)?'no-cache':path&&path!=='index.html'?'public,max-age=60':'no-cache',...(asset.sha256?{'etag':'"'+asset.sha256+'"'}:{}),'content-security-policy':sandboxAsset?sandboxCsp:CSP,...(sandboxAsset?{'access-control-allow-origin':'*','cross-origin-resource-policy':'cross-origin'}:{}),'x-content-type-options':'nosniff','referrer-policy':'same-origin','permissions-policy':'camera=(), microphone=(), geolocation=()','x-atlas-quant-build':BUILD_ID}});
 }catch(err){const e=safeError(err);return json({error:{code:e.code,message:e.message}},e.status);}},
 async scheduled(event,env,ctx){ctx.waitUntil((async()=>{await env.DB.prepare('DELETE FROM rate_buckets WHERE expires_at<?').bind(NOW()).run();const cutoff=new Date(Date.now()-30*86400000).toISOString();const jobs=await env.DB.prepare("SELECT id,dataset_key FROM jobs WHERE created_at<? AND dataset_key IS NOT NULL AND status NOT IN ('queued','running') LIMIT 100").bind(cutoff).all();for(const j of jobs.results){await env.ARTIFACTS.delete(j.dataset_key);await env.DB.prepare('UPDATE jobs SET dataset_key=NULL WHERE id=?').bind(j.id).run();}await cleanupFailedForecastSnapshots(env,cutoff);await cleanupAbandonedBundles(env,cutoff);})());}
};
