import {ApiError,validateStrategy,validateFactor,validateDataset} from './validation.mjs';
// Build injects WEB_ASSETS, CATALOG, BUILD_ID without credentials.
const NOW=()=>new Date().toISOString();
const random=()=>crypto.randomUUID();
const json=(v,status=200,headers={})=>new Response(JSON.stringify(v),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store','x-content-type-options':'nosniff',...headers}});
const parse=(v,fallback=null)=>{try{return JSON.parse(v);}catch{return fallback;}};
const safeError=e=>e instanceof ApiError?e:new ApiError('SERVER_ERROR','服务暂时无法完成请求，请稍后重试。',500);
async function sha(s){return [...new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s)))].map(x=>x.toString(16).padStart(2,'0')).join('');}
async function body(req,max=100000){const len=Number(req.headers.get('content-length')||0);if(len>max)throw new ApiError('TOO_LARGE','请求超过大小限制',413);let text='',bytes=0;const reader=req.body?.getReader(),decoder=new TextDecoder('utf-8',{fatal:true});try{if(reader)while(true){const {done,value}=await reader.read();if(done)break;bytes+=value.byteLength;if(bytes>max){await reader.cancel();throw new ApiError('TOO_LARGE','请求超过大小限制',413);}text+=decoder.decode(value,{stream:true});}text+=decoder.decode();return JSON.parse(text);}catch(e){if(e instanceof ApiError)throw e;throw new ApiError('INVALID_JSON','请求必须为 UTF-8 JSON');}finally{reader?.releaseLock();}}
function checkOrigin(req){const origin=req.headers.get('origin');if(origin&&origin!==new URL(req.url).origin)throw new ApiError('FORBIDDEN_ORIGIN','仅允许本站发起此操作',403);if(req.headers.get('sec-fetch-site')==='cross-site')throw new ApiError('FORBIDDEN_ORIGIN','跨站请求已拒绝',403);if(!['GET','HEAD'].includes(req.method)&&!req.headers.get('content-type')?.startsWith('application/json'))throw new ApiError('CONTENT_TYPE','请使用 JSON 请求',415);}
async function rate(env,key,limit,seconds){const bucket=Math.floor(Date.now()/(seconds*1000));const k=`${key}:${bucket}`;const r=await env.DB.prepare('INSERT INTO rate_buckets(key,count,expires_at) VALUES(?,1,?) ON CONFLICT(key) DO UPDATE SET count=count+1 RETURNING count').bind(k,new Date((bucket+2)*seconds*1000).toISOString()).first();if(r.count>limit)throw new ApiError('RATE_LIMITED','请求较多，请稍后再试。',429);}
async function audit(env,owner,action,id,detail={}){await env.DB.prepare('INSERT INTO audit(id,owner,action,entity_id,detail,created_at) VALUES(?,?,?,?,?,?)').bind(random(),owner,action,id,JSON.stringify(detail),NOW()).run();}
function cookie(req){const m=/(?:^|;\s*)aq_session=([a-f0-9-]{36}\.[a-f0-9-]{36})(?:;|$)/.exec(req.headers.get('cookie')||'');return m?.[1];}
async function workspace(req,env,create=false){const token=cookie(req);if(token){const w=await env.DB.prepare('SELECT id,name,created_at FROM workspaces WHERE token_hash=?').bind(await sha(token)).first();if(w)return {workspace:w};}if(!create)throw new ApiError('SESSION_REQUIRED','请刷新页面以建立工作区',401);await rate(env,'session:'+await sha(req.headers.get('cf-connecting-ip')||'local'),40,3600);const secret=random()+'.'+random(),id=random(),name='我的研究工作区';await env.DB.prepare('INSERT INTO workspaces(id,token_hash,name,created_at) VALUES(?,?,?,?)').bind(id,await sha(secret),name,NOW()).run();return {workspace:{id,name},cookie:`aq_session=${secret}; HttpOnly; Secure; SameSite=Strict; Path=/quant/; Max-Age=31536000`};}
async function runnerState(env){const r=await env.DB.prepare("SELECT value,updated_at FROM meta WHERE key='runner'").first();const v=parse(r?.value,{});return {online:!!r&&Date.now()-Date.parse(r.updated_at)<120000,lastSeen:r?.updated_at||null,state:v.state||'offline',engineVersion:v.engineVersion||null};}
function strategyItem(r){return {id:r.id,name:r.name,version:r.version,strategy:parse(r.spec),createdAt:r.created_at,updatedAt:r.updated_at};}
function jobItem(r){return {id:r.id,name:r.name,status:r.status,dataSource:r.data_source,createdAt:r.created_at,updatedAt:r.updated_at,summary:parse(r.summary),error:parse(r.error),strategy:parse(r.spec)};}
function factorItem(r){return {id:r.id,name:r.name,description:r.description,expression:r.expression,direction:r.direction,category:r.category,author:r.author,license:r.license,sourceUrl:r.source_url,forkOf:r.fork_of,version:r.version,status:r.status,...parse(r.metadata,{}),createdAt:r.created_at};}
async function builtinAndCommunity(env){const rows=await env.DB.prepare("SELECT * FROM factors WHERE status='published' ORDER BY created_at DESC LIMIT 300").all();return [...CATALOG.factors.map(f=>({...f,author:'Atlas Quant',license:'Apache-2.0',version:1,status:'builtin'})),...rows.results.map(factorItem)];}
async function findFactor(env,id){const builtin=CATALOG.factors.find(f=>f.id===id);if(builtin)return {...builtin,author:'Atlas Quant',license:'Apache-2.0',version:1,status:'builtin'};const row=await env.DB.prepare("SELECT * FROM factors WHERE id=? AND status='published'").bind(id).first();return row?factorItem(row):null;}
function capability(env){return {demo:true,upload:true,tushareHosted:env.TUSHARE_PUBLIC_AUTHORIZED==='true',localTushare:true};}
async function authorizeRunner(req,env){const value=req.headers.get('authorization')||'';if(!env.RUNNER_SECRET||await sha(value)!==await sha('Bearer '+env.RUNNER_SECRET))throw new ApiError('UNAUTHORIZED','需要计算服务凭据',401);}
async function enqueue(env,owner,input,internal=false){const strategy=validateStrategy(input.strategy);const ds=input.dataSource;if(!['demo','upload','tushare'].includes(ds))throw new ApiError('INVALID_SOURCE','请选择数据来源');if(ds==='tushare'&&!internal&&env.TUSHARE_PUBLIC_AUTHORIZED!=='true')throw new ApiError('DATA_AUTHORIZATION_REQUIRED','托管 Tushare 数据接入尚未开放。请使用个人本地适配器或导入有权使用的数据。',403);
 await rate(env,'runs:'+owner,20,86400);let dataset;if(ds==='upload')dataset=validateDataset(input.dataset,strategy);const active=await env.DB.prepare("SELECT count(*) n FROM jobs WHERE owner=? AND status IN ('queued','running')").bind(owner).first();if(active.n)throw new ApiError('JOB_ACTIVE','工作区已有实验运行中，请等待或取消。',409);const total=await env.DB.prepare("SELECT count(*) n FROM jobs WHERE status IN ('queued','running')").first();if(total.n>=30)throw new ApiError('QUEUE_FULL','计算队列已满，请稍后再试。',503);
 const id=random(),key=dataset?`datasets/${owner}/${id}.json`:null,time=NOW();if(key)await env.ARTIFACTS.put(key,JSON.stringify(dataset),{httpMetadata:{contentType:'application/json'}});
 // Single statement atomically enforces one active run per workspace.
 const r=await env.DB.prepare("INSERT INTO jobs(id,owner,name,status,data_source,spec,dataset_key,created_at,updated_at) SELECT ?,?,?, 'queued',?,?,?,?,? WHERE NOT EXISTS(SELECT 1 FROM jobs WHERE owner=? AND status IN ('queued','running')) AND (SELECT count(*) FROM jobs WHERE status IN ('queued','running'))<30").bind(id,owner,strategy.name,ds,JSON.stringify(strategy),key,time,time,owner).run();if(!r.meta.changes){if(key)await env.ARTIFACTS.delete(key);throw new ApiError('JOB_ACTIVE','已有实验运行中',409);}await audit(env,owner,'run.created',id,{dataSource:ds,strategyHash:await sha(JSON.stringify(strategy))});return {id,status:'queued',name:strategy.name,dataSource:ds,createdAt:time};
}
async function runnerApi(req,env,path){await authorizeRunner(req,env);if(req.method!=='POST')throw new ApiError('METHOD','需要 POST',405);const input=await body(req,path==='/runner/complete'?13*1024*1024:100000);const now=NOW();
 if(path==='/runner/heartbeat'||path==='/runner/claim'){await env.DB.prepare("INSERT INTO meta(key,value,updated_at) VALUES('runner',?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value,updated_at=excluded.updated_at").bind(JSON.stringify({state:input.state||input.status||'ready',engineVersion:input.engineVersion||null}),now).run();}
 if(path==='/runner/heartbeat'){if(input.id&&input.leaseToken){const updated=await env.DB.prepare("UPDATE jobs SET lease_until=?,updated_at=? WHERE id=? AND lease_token=? AND status='running'").bind(new Date(Date.now()+20*60000).toISOString(),now,input.id,input.leaseToken).run();return json({ok:true,leaseValid:!!updated.meta.changes,cancelled:!updated.meta.changes});}return json({ok:true});}
 if(path==='/runner/enqueue'){const owner='operator';return json({job:await enqueue(env,owner,input,true)},201);}
 if(path==='/runner/inspect'){const r=await env.DB.prepare('SELECT * FROM jobs WHERE id=?').bind(String(input.id||'')).first();if(!r)throw new ApiError('NOT_FOUND','实验不存在',404);const obj=r.result_key?await env.ARTIFACTS.get(r.result_key):null;return json({job:jobItem(r),result:obj?await obj.json():null});}
 if(path==='/runner/claim'){
 await env.DB.prepare("UPDATE jobs SET status='failed',error=?,updated_at=? WHERE status='running' AND lease_until<?").bind(JSON.stringify({code:'RUNNER_INTERRUPTED',message:'计算服务中断，此次实验未完成。请确认后重新运行。'}),now,now).run();
 const lease=random();const r=await env.DB.prepare("UPDATE jobs SET status='running',lease_token=?,lease_until=?,updated_at=? WHERE id=(SELECT id FROM jobs WHERE status='queued' ORDER BY created_at LIMIT 1) AND status='queued' RETURNING *").bind(lease,new Date(Date.now()+20*60000).toISOString(),now).first();if(!r)return json({job:null});const dataset=r.dataset_key?await env.ARTIFACTS.get(r.dataset_key):null;return json({job:{id:r.id,workspaceId:r.owner,leaseToken:lease,strategy:parse(r.spec),dataSource:r.data_source,dataset:dataset?await dataset.json():null}});
 }
 if(path==='/runner/complete'){
 const r=await env.DB.prepare("SELECT * FROM jobs WHERE id=? AND lease_token=? AND status IN ('running','completed','failed','cancelled')").bind(String(input.id||''),String(input.leaseToken||'')).first();if(!r)throw new ApiError('STALE_LEASE','实验已取消或运行租约失效',409);if(r.status!=='running'){if(r.status==='cancelled'||(r.status==='failed'&&parse(r.error)?.code==='RUNNER_INTERRUPTED'))return json({ok:true,status:r.status,ignored:true});if(r.status==='completed'&&input.result){const previous=await env.ARTIFACTS.get(r.result_key);if(previous&&await sha(await previous.text())===await sha(JSON.stringify(input.result)))return json({ok:true,status:'completed',idempotent:true});}if(r.status==='failed'&&input.error&&parse(r.error)?.code===String(input.error.code||'COMPUTE_FAILED')&&parse(r.error)?.message===String(input.error.message||'实验未完成').slice(0,700))return json({ok:true,status:'failed',idempotent:true});throw new ApiError('COMPLETION_CONFLICT','此实验已有不同的终态',409);}if(input.error){const error={code:String(input.error.code||'COMPUTE_FAILED').slice(0,80),message:String(input.error.message||'实验未完成').slice(0,700)};await env.DB.prepare("UPDATE jobs SET status='failed',error=?,updated_at=? WHERE id=? AND lease_token=? AND status='running'").bind(JSON.stringify(error),now,r.id,r.lease_token).run();return json({ok:true,status:'failed'});}
 const result=input.result;if(!result||!result.metrics||!Array.isArray(result.equity)||!result.selection||!result.provenance)throw new ApiError('INVALID_RESULT','研究报告缺少必需的计算证据');const resultText=JSON.stringify(result);if(new TextEncoder().encode(resultText).byteLength>12*1024*1024)throw new ApiError('RESULT_TOO_LARGE','研究报告超过 12 MiB',413);if(/"(?:token|serviceToken|api_key|password|authorization)"\s*:/i.test(resultText))throw new ApiError('SENSITIVE_RESULT','报告包含不应公开的凭据字段');const resultHash=await sha(resultText);const resultKey=`results/${r.owner}/${r.id}/${resultHash}.json`;await env.ARTIFACTS.put(resultKey,resultText,{httpMetadata:{contentType:'application/json'}});const summary={...result.metrics,winner:result.selection.winner,evidenceStatus:result.selection.evidenceStatus,engineVersion:result.engineVersion};const updated=await env.DB.prepare("UPDATE jobs SET status='completed',result_key=?,summary=?,updated_at=? WHERE id=? AND lease_token=? AND status='running'").bind(resultKey,JSON.stringify(summary),now,r.id,r.lease_token).run();if(!updated.meta.changes){const current=await env.DB.prepare('SELECT status,result_key,error FROM jobs WHERE id=?').bind(r.id).first();if(current?.status==='completed'&&current.result_key===resultKey)return json({ok:true,status:'completed',idempotent:true});if(current?.result_key!==resultKey)await env.ARTIFACTS.delete(resultKey);if(current?.status==='cancelled'||(current?.status==='failed'&&parse(current.error)?.code==='RUNNER_INTERRUPTED'))return json({ok:true,status:current.status,ignored:true});throw new ApiError('COMPLETION_CONFLICT','此实验已有不同的终态',409);}if(r.dataset_key)await env.ARTIFACTS.delete(r.dataset_key);await audit(env,r.owner,'run.completed',r.id,{resultHash:await sha(resultText)});return json({ok:true,status:'completed'});
 }
 throw new ApiError('NOT_FOUND','接口不存在',404);
}
async function api(req,env,path){checkOrigin(req);if(path.startsWith('/runner/'))return runnerApi(req,env,path);
 if(path==='/health')return json({ok:true,service:'Atlas Quant',version:BUILD_ID,runner:await runnerState(env),capabilities:capability(env)});
 if(path==='/catalog'&&req.method==='GET')return json({...CATALOG,factors:await builtinAndCommunity(env),dataSources:[{id:'demo',name:'合成数据教程',available:true,description:'完全合成的教学数据，不代表任何证券实际表现'},{id:'upload',name:'导入个人数据',available:true},{id:'tushare',name:'Tushare',available:capability(env).tushareHosted,localAdapter:true}],limits:{maxSymbols:20,minSymbols:3,maxFactors:12,maxRows:45000,maxActiveRuns:1},sourceUrl:env.SOURCE_URL||'/quant/source.zip'});
 if(path==='/factors'&&req.method==='GET')return json({items:await builtinAndCommunity(env)});
 if(path.startsWith('/factors/')&&req.method==='GET'){const id=path.split('/')[2],item=await findFactor(env,id);if(!item)throw new ApiError('NOT_FOUND','因子不存在',404);return json({item});}
 if(path==='/session'&&req.method==='GET'){const w=await workspace(req,env,true);return json({workspace:w.workspace,runner:await runnerState(env),capabilities:capability(env),sourceUrl:env.SOURCE_URL||'/quant/source.zip'},200,w.cookie?{'set-cookie':w.cookie}:{});}
 const {workspace:w}=await workspace(req,env);const owner=w.id;await rate(env,'requests:'+owner,180,60);
 if(path==='/strategies'&&req.method==='GET'){const rows=await env.DB.prepare('SELECT * FROM strategies WHERE owner=? ORDER BY updated_at DESC LIMIT 200').bind(owner).all();return json({items:rows.results.map(strategyItem)});}
 if(path==='/strategies'&&req.method==='POST'){const {strategy}=await body(req);const s=validateStrategy(strategy);const n=await env.DB.prepare('SELECT count(*) n FROM strategies WHERE owner=?').bind(owner).first();if(n.n>=200)throw new ApiError('LIMIT','最多保存 200 个策略');const id=random(),time=NOW(),spec=JSON.stringify(s);await env.DB.batch([env.DB.prepare('INSERT INTO strategies(id,owner,name,spec,created_at,updated_at) VALUES(?,?,?,?,?,?)').bind(id,owner,s.name,spec,time,time),env.DB.prepare('INSERT INTO strategy_versions(strategy_id,version,spec,created_at) VALUES(?,1,?,?)').bind(id,spec,time)]);return json({item:{id,name:s.name,strategy:s,version:1,createdAt:time,updatedAt:time}},201);}
 if(path.startsWith('/strategies/')){const id=path.split('/')[2];const row=await env.DB.prepare('SELECT * FROM strategies WHERE id=? AND owner=?').bind(id,owner).first();if(!row)throw new ApiError('NOT_FOUND','策略不存在',404);if(req.method==='GET')return json({item:strategyItem(row)});if(req.method==='DELETE'){await env.DB.batch([env.DB.prepare('DELETE FROM strategy_versions WHERE strategy_id=?').bind(id),env.DB.prepare('DELETE FROM strategies WHERE id=? AND owner=?').bind(id,owner)]);return json({ok:true});}if(req.method==='PUT'){const {strategy,version}=await body(req);if(version!==row.version)throw new ApiError('REVISION_CONFLICT','另一窗口已更新策略，请重新载入后再修改。',409);const s=validateStrategy(strategy),time=NOW(),spec=JSON.stringify(s);const r=await env.DB.prepare('UPDATE strategies SET name=?,spec=?,version=version+1,updated_at=? WHERE id=? AND owner=? AND version=? RETURNING *').bind(s.name,spec,time,id,owner,version).first();if(!r)throw new ApiError('REVISION_CONFLICT','版本冲突，请重新载入',409);await env.DB.prepare('INSERT OR IGNORE INTO strategy_versions(strategy_id,version,spec,created_at) VALUES(?,?,?,?)').bind(id,r.version,spec,time).run();return json({item:strategyItem(r)});}}
 if(path==='/runs'&&req.method==='GET'){const rows=await env.DB.prepare('SELECT * FROM jobs WHERE owner=? ORDER BY created_at DESC LIMIT 100').bind(owner).all();return json({items:rows.results.map(jobItem)});}
 if(path==='/runs'&&req.method==='POST'){const input=await body(req,8_100_000);return json({job:await enqueue(env,owner,input)},202);}
 if(path.startsWith('/runs/')){const [,,id,action]=path.split('/');const r=await env.DB.prepare('SELECT * FROM jobs WHERE id=? AND owner=?').bind(id,owner).first();if(!r)throw new ApiError('NOT_FOUND','实验不存在',404);if(action==='cancel'&&req.method==='POST'){const x=await env.DB.prepare("UPDATE jobs SET status='cancelled',updated_at=? WHERE id=? AND owner=? AND status IN ('queued','running')").bind(NOW(),id,owner).run();if(r.dataset_key&&x.meta.changes)await env.ARTIFACTS.delete(r.dataset_key);return json({ok:true,status:x.meta.changes?'cancelled':r.status});}if(req.method==='GET'){const obj=r.result_key?await env.ARTIFACTS.get(r.result_key):null;const result=obj?await obj.json():null;return json({job:jobItem(r),result},200,action==='export'?{'content-disposition':`attachment; filename="atlas-quant-${id}.json"`}:{});}}
 if(path==='/factors'&&req.method==='POST'){await rate(env,'factor:'+owner,10,86400);const f=validateFactor(await body(req,12000));if(f.forkOf&&!await findFactor(env,f.forkOf))throw new ApiError('INVALID_FORK','原始因子不存在');const id='community_'+random(),time=NOW();await env.DB.prepare("INSERT INTO factors(id,owner,name,description,expression,direction,category,author,license,source_url,fork_of,status,metadata,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,'published',?,?)").bind(id,owner,f.name,f.description,f.expression,f.direction,f.category,f.author,f.license,f.sourceUrl,f.forkOf,JSON.stringify({...f.metadata,reviewStatus:'community_unreviewed'}),time).run();await audit(env,owner,'factor.published',id,{expressionHash:await sha(f.expression)});return json({item:{id,...f,status:'published',reviewStatus:'community_unreviewed',version:1,createdAt:time}},201);}
 if(path.startsWith('/factors/')&&req.method==='DELETE'){const id=path.split('/')[2];const r=await env.DB.prepare("UPDATE factors SET status='withdrawn' WHERE id=? AND owner=?").bind(id,owner).run();if(!r.meta.changes)throw new ApiError('NOT_FOUND','找不到你发布的因子',404);return json({ok:true});}
 throw new ApiError('NOT_FOUND','接口不存在',404);
}
const CSP="default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; font-src 'self'; connect-src 'self'; object-src 'none'; base-uri 'self'; frame-ancestors 'none'; form-action 'self'";
export default {
 async fetch(req,env,ctx){const url=new URL(req.url);try{
 if(url.pathname==='/quant')return Response.redirect(url.origin+'/quant/'+url.search,308);
 if(url.pathname.startsWith('/quant/api/'))return await api(req,env,url.pathname.slice('/quant/api'.length).replace(/\/$/,'')||'/');
 if(!['GET','HEAD'].includes(req.method))return json({error:{code:'METHOD',message:'方法不支持'}},405);
 if(url.pathname==='/quant/source.zip'){const obj=await env.ARTIFACTS.get('public/source.zip');if(!obj)return json({error:{code:'NOT_READY',message:'源码包正在准备'}},503);return new Response(req.method==='HEAD'?null:obj.body,{headers:{'content-type':'application/zip','content-disposition':'attachment; filename="atlas-quant-source.zip"','cache-control':'public,max-age=300'}});}
 const path=url.pathname.replace(/^\/quant\/?/,'');const asset=WEB_ASSETS[path||'index.html']||(path.includes('.')?null:WEB_ASSETS['index.html']);if(!asset)return new Response('Not found',{status:404});return new Response(req.method==='HEAD'?null:asset.body,{headers:{'content-type':asset.type,'cache-control':path&&path!=='index.html'?'public,max-age=60':'no-cache','content-security-policy':CSP,'x-content-type-options':'nosniff','referrer-policy':'same-origin','permissions-policy':'camera=(), microphone=(), geolocation=()','x-atlas-quant-build':BUILD_ID}});
 }catch(err){const e=safeError(err);return json({error:{code:e.code,message:e.message}},e.status);}},
 async scheduled(event,env,ctx){ctx.waitUntil((async()=>{await env.DB.prepare('DELETE FROM rate_buckets WHERE expires_at<?').bind(NOW()).run();const cutoff=new Date(Date.now()-30*86400000).toISOString();const jobs=await env.DB.prepare("SELECT id,dataset_key FROM jobs WHERE created_at<? AND dataset_key IS NOT NULL AND status NOT IN ('queued','running') LIMIT 100").bind(cutoff).all();for(const j of jobs.results){await env.ARTIFACTS.delete(j.dataset_key);await env.DB.prepare('UPDATE jobs SET dataset_key=NULL WHERE id=?').bind(j.id).run();}})());}
};
