/* Atlas Quant v2: accessible research composer and independent studio workspaces. */
(() => {
  'use strict';
  window.AtlasQuantV2 = {create(C) {
    const {state:s,esc:e,icon:i,api,toast,render,persistDraft,normalizeStrategy,clone,field,fmt,pct,dateText} = C;
    const stages=[['data','database','数据与股票池'],['factors','layers','因子研究'],['targets','chart','观察与检验'],['models','model','模型与拟合'],['validation','shield','时间验证'],['portfolio','wallet','组合与成本'],['reports','chart','研究报告'],['code','code','代码与 AI 审阅']];
    const models={factor_score:['因子评分','透明的基准排序，用来判断模型是否真正增加价值。','基准'],ridge:['Ridge','适合相关因子，使用 L2 正则化控制系数。','线性'],elastic_net:['Elastic Net','L1 与 L2 正则化，适合冗余特征与稀疏信号。','线性'],bayesian_ridge:['Bayesian Ridge','贝叶斯正则化的线性回归。','统计'],huber:['Huber','降低异常标签对线性拟合的影响。','稳健'],hist_gradient_boosting:['Histogram Gradient Boosting','学习非线性与因子交互，使用有限搜索范围。','提升树'],random_forest:['Random Forest','不同树的集成，探索非线性结构。','集成'],extra_trees:['Extra Trees','随机化分割的树集成，作为另一种非线性候选。','集成']};
    const v={ready:false,errors:[],universes:[],featuredUniverses:[],universeTotal:0,universeAllTotal:0,membersQuery:'',membersPage:1,universeCategories:[],universeLoading:false,catalogSummary:null,universe:null,universeQuery:'',universeCategory:'index',universePage:1,presets:{goals:[],packs:[],strategies:[]},sources:[],sourceArchitecture:null,sourceAdapters:[],catalog:{items:[],total:0,page:1,pageSize:24},filters:{q:'',category:'',database:'',availability:'',page:1},catalogLoading:false,catalogError:'',catalogTab:'factors',fieldCatalog:{items:[],total:0,page:1,pageSize:24},fieldFilters:{q:'',database:'',page:1},fieldLoading:false,group:'',mapping:{alias:'',fieldId:'',unitCode:'',records:'[]'},mappingJson:'',goal:'',forecastResult:null,forecastJob:null,forecastLoading:false,forecastRunId:'',builder:{name:'我的自定义因子',field:'close',transform:'returns',window:20,expression:'returns(close,20)',direction:1},lint:null,lintBusy:false,editorLanguage:'dsl',code:{dsl:'returns(close,20)',python:'# 在隔离的浏览器 Python 中研究上传的数据\n# data 是当前已导入数据的记录列表；没有上传时为空。\nimport json\nfrom collections import Counter\n\nprint("数据行数:", len(data))\ncounts = Counter(row["ts_code"] for row in data)\nprint(json.dumps(dict(counts), ensure_ascii=False, indent=2))\n\n# result 会作为结构化输出显示\nresult = {"rows": len(data), "symbols": len(counts)}\n',json:''},projects:[],projectId:null,projectVersion:null,projectName:'我的研究脚本',projectSaving:false,review:null,reviewBusy:false,pythonBusy:false,pythonOutput:null,applied:new Set(),selectionRequest:0,mode:'simple'};
    try{const d=JSON.parse(localStorage.getItem('atlas-quant-editor-v2')||'null');if(d?.code)for(const k of ['dsl','python'])if(typeof d.code[k]==='string')v.code[k]=d.code[k];}catch{}
    const isStudio=()=>s.view==='studio';
    const stage=()=>stages.some(x=>x[0]===s.studioStep)?s.studioStep:'data';
    const status=x=>typeof x?.availability==='string'?x.availability:(x?.availability?.status||(['ready','partial','schema_only','needs_mapping','unavailable','requires_data'].includes(x?.status)?x.status:null)||(x?.expression?'ready':'unknown'));
    const availability=x=>({ready:'可研究',partial:'部分接入',schema_only:'仅字段定义',needs_mapping:'待时间 / 标的映射',unavailable:'暂不可用',requires_data:'需要补充数据',unknown:'待核验'}[status(x)]||status(x));
    const reason=x=>x?.availability?.reason||x?.availabilityReason||x?.reason||'';
    const ready=x=>status(x)==='ready';
    const requiredFields=x=>x?.requiredFields||x?.fields||x?.metadata?.fields||(x?.alias?[x.alias]:[]);
    function expectedFieldId(alias,x){const fields=requiredFields(x);if(x?.fieldIds?.[alias])return x.fieldIds[alias];if(x?.fieldId&&fields.length===1&&fields[0]===alias)return x.fieldId;if(x?.alias===alias&&x?.id)return x.id;const field=v.fieldCatalog.items.find(f=>f.alias===alias);if(field)return field.id;const recipe=C.factors().find(f=>f.fieldId&&(f.requiredFields||[]).length===1&&f.requiredFields[0]===alias);return recipe?.fieldId||null;}
    function mapped(x){const fields=requiredFields(x);if(!fields.length||x?.numericEligible===false)return false;return fields.every(alias=>{const binding=s.strategy.dataBindings?.pcd?.[alias],expected=expectedFieldId(alias,x);return alias.startsWith('pcd_')&&(!(x?.fieldId||x?.status==='schema_recipe'||x?.alias)||Boolean(expected))&&binding&&Array.isArray(binding.records)&&binding.records.length>0&&typeof binding.unitCode==='string'&&binding.unitCode.trim()&&typeof binding.fieldId==='string'&&binding.fieldId.trim()&&(!expected||binding.fieldId===expected)&&binding.records.every(r=>s.strategy.universe.symbols.includes(r.ts_code)&&typeof r.entityId==='string'&&r.entityId.trim()&&typeof r.recordId==='string'&&r.recordId.trim());});}
    const uploadEvidenceCache=new WeakMap();
    function uploadEvidence(dataset){let cached=uploadEvidenceCache.get(dataset);if(cached)return cached;const rows=dataset.rows||[],metadata=dataset.provenance?.externalFields||{},columns=new Set(),external={};for(const row of rows)for(const key of Object.keys(row))columns.add(key);for(const [alias,m] of Object.entries(metadata)){const companion=alias+'__available_date';let valid=/^(pcd|fd|ext|model)_[a-z0-9_]{1,60}$/.test(alias)&&m&&typeof m==='object'&&['number','decimal','integer'].includes(m.dataType)&&m.availabilityPolicy==='point_in_time_asof'&&m.availableDateColumn===companion&&typeof m.source==='string'&&m.source.trim()&&typeof m.path==='string'&&m.path.trim()&&columns.has(alias)&&columns.has(companion),observed=0;if(valid)for(const row of rows){const value=row[alias];if(value===undefined||value===null)continue;const available=String(row[companion]||''),date=new Date(`${available.slice(0,4)}-${available.slice(4,6)}-${available.slice(6,8)}T00:00:00Z`);if(typeof value!=='number'||!Number.isFinite(value)||!/^\d{8}$/.test(available)||Number.isNaN(+date)||date.toISOString().slice(0,10).replaceAll('-','')!==available||available>String(row.trade_date)){valid=false;break;}observed++;}external[alias]={valid:Boolean(valid&&observed),path:m?.path};}cached={columns,external};uploadEvidenceCache.set(dataset,cached);return cached;}
    function uploaded(x){const fields=requiredFields(x);if(s.dataSource!=='upload'||!s.dataset?.rows?.length||!fields.length||x?.numericEligible===false)return false;const evidence=uploadEvidence(s.dataset);return fields.every(alias=>{if(!/^(pcd|fd|ext|model)_/.test(alias))return evidence.columns.has(alias);const info=evidence.external[alias],expected=expectedFieldId(alias,x);return info?.valid&&(!alias.startsWith('pcd_')||!expected||info.path===expected);});}
    const canUse=x=>ready(x)||mapped(x)||uploaded(x);
    const contextualStatus=x=>!ready(x)?mapped(x)?'已配置映射，运行时校验':uploaded(x)?'已导入 PIT 字段，运行时校验':'':'';
    const contextualChip=x=>contextualStatus(x)?`<span class="v2-context-status">${e(contextualStatus(x))}</span>`:'';
    const databaseName=x=>({MKT:'MKT · 市场数据',EXT:'EXT · 外部研究与估计',PCD:'PCD · 公司事实',MODEL:'MODEL · 派生研究',FD:'财务指标适配器',PCD_DERIVED:'PCD 衍生定义',COMMUNITY:'社区贡献'}[x]||x);
    const categoryName=x=>({area:'地域',exchange:'交易所',index:'精选指数',industry:'行业',sw_industry:'申万行业',industry_exchange:'行业 × 交易所',industry_region:'行业 × 地域',market:'市场板块'}[x]||x);
    const subsetRule=u=>u?.recommendationMethod?.includes('symbol_code')?`目录默认按代码升序取前 ${u.recommendedSymbols?.length||20} 只，仅为研究子集，不代表收益筛选。`:'目录推荐仅定义研究范围，不代表收益筛选；可自行调整成员。';
    const itemName=x=>x.name||x.label||x.id||x.field||'未命名';
    const count=n=>n!==null&&n!==undefined&&Number.isFinite(Number(n))?Number(n).toLocaleString():'—';
    const labelOptions=(arr,val)=>arr.map(x=>{const key=typeof x==='string'?x:x.id||x.value||x.name;return `<option value="${e(key)}" ${key===val?'selected':''}>${e(typeof x==='string'?databaseName(x):x.name||x.label||key)}</option>`;}).join('');
    const chip=x=>`<span class="v2-status ${ready(x)?'ready':''}"><i></i>${e(availability(x))}</span>`;
    const section=(title,body,extra='')=>`<section class="panel v2-panel"><div class="v2-panel-head"><h2>${title}</h2>${extra}</div>${body}</section>`;
    const empty=(text)=>`<div class="v2-empty">${i('search')}<p>${e(text)}</p></div>`;
    function header(kicker,title,description,buttons=''){return `<div class="v2-heading"><div><div class="eyebrow">${kicker}</div><h1>${title}</h1><p>${description}</p></div>${buttons?`<div class="actions">${buttons}</div>`:''}</div>`;}
    const action=(id,text,ico='',cls='ghost',attrs='')=>`<button class="btn ${cls}" data-v2="${id}" ${attrs}>${ico?i(ico):''}${text}</button>`;
    const legacy=(id,text,ico='',cls='ghost',attrs='')=>`<button class="btn ${cls}" data-action="${id}" ${attrs}>${ico?i(ico):''}${text}</button>`;
    const link=(href,text,ico='',cls='ghost')=>`<a class="btn ${cls}" href="#${href}">${ico?i(ico):''}${text}</a>`;
    const researchActions=()=>`${legacy('save',s.saving?'保存中…':'保存','save','ghost',s.saving?'disabled':'')}${legacy('run',s.submitting?'提交中…':'运行研究','play','primary',s.submitting?'disabled':'')}`;
    const flow=window.AtlasResearchFlow.create({...C,v,section,header,action,legacy,link,universeBrowser,recipeGroups,catalogBrowser,researchName,mappingEditor,chip,ready,reason,forecastPreview});
    function renderApp(){
      const studio=isStudio(),current=stage();v.mode=studio?'studio':'simple';
      const normal=[['dashboard','grid','研究首页'],['research/universe','workflow','逐步研究'],['strategies','save','我的策略'],['runs','chart','研究记录'],['factors','users','开放社区']];
      const nav=studio?stages:normal;
      const active=studio?current:['research','lab'].includes(s.view)?'research/universe':s.view;
      const title=studio?stages.find(x=>x[0]===current)[2]:normal.find(x=>x[0]===active)?.[2]||'研究工作区';
      const source=C.safeUrl(s.session?.sourceUrl||s.catalog?.sourceUrl||'');
      return `<div class="v2-shell ${studio?'v2-studio':'v2-simple'}"><aside class="v2-sidebar"><a class="v2-brand" href="#dashboard"><span class="atlas-mark">A</span><span>atlas <strong>quant</strong><small>OPEN RESEARCH PLATFORM</small></span></a><div class="v2-mode-switch"><a href="#dashboard" class="${!studio?'active':''}">轻松研究</a><a href="#studio/${current}" class="${studio?'active':''}">Quant Studio</a></div><div class="v2-nav-label">${studio?'RESEARCH WORKSPACE':'YOUR QUANT'}</div><nav aria-label="${studio?'Studio 研究步骤':'主要导航'}">${nav.map(([id,ico,text],index)=>`<a href="#${studio?'studio/':''}${id}" class="v2-nav ${active===id?'active':''}" ${active===id?'aria-current="page"':''}>${i(ico)}<span>${text}</span>${studio?`<small>${String(index+1).padStart(2,'0')}</small>`:''}</a>`).join('')}</nav><div class="v2-sidebar-end"><div class="v2-session"><i class="dot ${s.session?.runner?.online?'online':''}"></i>${s.session?.runner?.online?'研究计算在线':'等待计算节点'}<small>策略保存在当前浏览器工作区</small></div><a class="v2-nav" href="/cn/terminal" target="_blank" rel="noopener">${i('external')}<span>Atlas Terminal</span></a>${source?`<a class="v2-nav" href="${e(source)}" target="_blank" rel="noopener noreferrer">${i('code')}<span>开源代码</span></a>`:''}</div></aside><main class="v2-main" id="main-content" tabindex="-1"><header class="v2-topbar"><a href="#dashboard" class="v2-mobile-logo">atlas <strong>quant</strong></a><div class="v2-breadcrumb">${studio?'Quant Studio':'Atlas Quant'}<span>/</span><strong>${e(title)}</strong></div><div class="v2-topbar-right">${studio?`<span class="v2-draft">${e(s.strategy.name)} · ${s.dirty?'未保存':'已保存'}</span>`:'<span class="v2-edition">RESEARCH PLATFORM · 0.3</span>'}<a class="btn small ghost" href="#${studio?'research/universe':'studio/data'}">${i(studio?'workflow':'code')}${studio?'轻松模式':'Quant Studio'}</a></div></header>${studio?`<div class="v2-studio-mobile-nav">${stages.map(([id,,text])=>`<a href="#studio/${id}" class="${current===id?'active':''}">${text}</a>`).join('')}</div>`:`<div class="v2-simple-mobile-nav">${normal.map(([id,,text])=>`<a href="#${id}" class="${active===id?'active':''}">${text}</a>`).join('')}</div>`}<div class="v2-content">${s.error?`<div class="notice error" role="alert">${e(s.error)} ${legacy('refresh','重新连接')}</div>`:''}${v.errors.length?`<div class="notice info">${i('info')}<div>部分目录未就绪：${e(v.errors.join('；'))} ${action('reload-catalogs','重试')}</div></div>`:''}${studio?studioScreen(current):s.view==='dashboard'?home():['lab','research'].includes(s.view)?composer():s.view==='strategies'?saved():s.view==='factors'?community():C.runsView()}</div><footer class="v2-footer"><span>ATLAS QUANT / OPEN SOURCE RESEARCH</span><span>数据来源与研究假设始终可追溯</span></footer></main></div>`;
    }
    function home(){return flow.home();}
    function saved(){return `${header('MY STRATEGIES','我的策略','私有策略、版本与可复现配置。',legacy('import-strategy','导入 JSON','upload')+action('fresh','新建研究','plus','primary'))}<section class="panel">${s.strategies.length?C.strategyTable():empty('还没有保存的策略。完成配置后点击保存，你的策略会出现在这里。')}</section><p class="footnote">当前工作区由浏览器私有会话识别。导出策略与报告可保留研究；清除网站数据可能失去该工作区的访问。</p>`;}
    function researchName(){return `<label class="v2-name"><span>当前研究</span><input id="strategy-name" aria-label="策略名称" value="${e(s.strategy.name)}" maxlength="80"><small>${s.strategyId?`v${e(s.strategyVersion||1)}`:'新草稿'}</small></label>`;}
    function composer(){return flow.composer();}
    function universeBrowser(filters=true,pageSize=12){
      pageSize=12;const page=v.universePage,rows=filters?v.universes:v.featuredUniverses.slice(0,6);
      return `<div class="v2-universe-browser">${filters?`<div class="v2-filterbar"><label class="v2-search">${i('search')}<input id="v2-universe-search" aria-label="搜索股票池" placeholder="搜索股票池、行业、主题…" value="${e(v.universeQuery)}"></label><select id="v2-universe-category" aria-label="股票池类别"><option value="all">全部类别</option>${labelOptions(v.universeCategories.map(x=>({id:typeof x==='string'?x:x.category,name:categoryName(typeof x==='string'?x:x.category)})),v.universeCategory)}</select></div>`:''}<div class="v2-universe-grid">${v.universeLoading?'<div class="loading-line"><span class="spinner"></span>读取股票池…</div>':rows.map(x=>`<article class="v2-universe ${v.universe?.id===x.id?'selected':''}" ${ready(x)?`data-v2-drag="universe:${e(x.id)}"`:''}><div class="v2-universe-top"><span>${e(categoryName(x.category||'精选'))}</span>${chip(x)}</div><h3>${e(itemName(x))}</h3><p>${e(x.curationRationale||x.description||'当前成员快照 · 研究范围定义')}</p><div class="v2-universe-bottom"><span>${count(x.symbolCount||x.symbols?.length)} <small>只 / 完整池</small></span>${action('universe',v.universe?.id===x.id?'再次纳入':'纳入集合',v.universe?.id===x.id?'check':'plus','subtle small',`data-id="${e(x.id)}" ${ready(x)?'':'disabled'}`)}</div>${!ready(x)&&reason(x)?`<small class="v2-availability-reason">${e(reason(x))}</small>`:''}</article>`).join('')||empty(v.ready?'没有匹配的股票池。':'正在加载股票池…')}</div>${filters?`<div class="v2-pagination"><span>${count(v.universeTotal)} 个股票池 · 第 ${page} / ${Math.max(1,Math.ceil(v.universeTotal/pageSize))} 页</span><div>${action('universe-page','上一页','','ghost small',`data-page="${page-1}" ${page<=1?'disabled':''}`)}${action('universe-page','下一页','','ghost small',`data-page="${page+1}" ${page*pageSize>=v.universeTotal?'disabled':''}`)}</div></div>`:''}</div>`;
    }
    function studioScreen(id){return ({data:dataScreen,factors:factorScreen,targets:targetScreen,models:modelScreen,validation:validationScreen,portfolio:portfolioScreen,reports:reportScreen,code:codeScreen}[id]||dataScreen)();}
    function studioHeading(title,description){return `${header(`QUANT STUDIO / ${stage().toUpperCase()}`,title,description,researchActions())}${researchName()}`;}
    function dataScreen(){return flow.studioData();}
    function memberPicker(u){const all=(u.symbols||[]).map(x=>typeof x==='string'?{code:x,name:''}:{code:x.ts_code||x.symbol,name:x.name||''}),query=v.membersQuery.trim().toLowerCase(),filtered=all.filter(x=>!query||`${x.code} ${x.name}`.toLowerCase().includes(query)),page=Math.min(v.membersPage,Math.max(1,Math.ceil(filtered.length/40))),items=filtered.slice((page-1)*40,page*40);return `<details open><summary>从完整成员中勾选（最多 50 只）</summary><label class="v2-search" style="margin-top:13px">${i('search')}<input id="v2-member-search" aria-label="搜索完整股票池成员" value="${e(v.membersQuery)}" placeholder="搜索代码或名称"></label><div class="v2-member-list">${items.map(x=>`<label><input type="checkbox" data-v2-member="${e(x.code)}" ${s.strategy.universe.symbols.includes(x.code)?'checked':''}><span>${e(x.code)}</span><small>${e(x.name)}</small></label>`).join('')||'<p class="footnote">没有匹配成员</p>'}</div>${pagination('member-page',page,filtered.length,40)}</details>`;}
    function mappingEditor(){const bindings=s.strategy.dataBindings?.pcd||{};return section('PCD 精确数据映射',`<div class="v2-panel-content"><p>目录字段与实际观测分别处理。映射需要你提供确定的实体、记录、单位和 A 股代码；系统不会按公司名称猜测。</p><p class="footnote">当前可见事实覆盖不足以证明 A 股历史覆盖。保存映射只记录配置，实际可用性由运行时校验。</p><div class="v2-binding-list">${Object.entries(bindings).map(([alias,b])=>`<div><strong>${e(alias)}</strong><p>${e(b.fieldId)} · ${e(b.unitCode)} · ${b.records?.length||0} 条记录映射</p>${action('remove-binding','移除','','subtle small',`data-id="${e(alias)}"`)}</div>`).join('')}</div><details class="v2-mapping-details" ${v.mapping.fieldId?'open':''}><summary>添加一个精确绑定</summary><form id="v2-mapping-form"><label class="field"><span>因子字段别名</span><input name="alias" value="${e(v.mapping.alias)}" placeholder="pcd_…" required pattern="pcd_[a-z0-9_]{1,60}"></label><label class="field"><span>PCD fieldId</span><input name="fieldId" value="${e(v.mapping.fieldId)}" required maxlength="220" placeholder="从数据库字段目录选择"></label><label class="field"><span>原始单位代码</span><input name="unitCode" value="${e(v.mapping.unitCode)}" required maxlength="80" placeholder="与源记录完全一致"></label><label class="field"><span>记录映射 · JSON 数组</span><textarea name="records" class="mono" required aria-label="PCD 精确记录映射">${e(v.mapping.records)}</textarea><small>每项必须包含 ts_code、entityId、recordId。1–50 条精确映射。</small></label><pre class="code-snippet">[{"ts_code":"600000.SH",
  "entityId":"填写真实实体 ID",
  "recordId":"填写真实记录 ID"}]</pre><button class="btn ghost" type="submit" style="margin-top:14px">保存绑定配置</button></form></details></div>`);}
    function factorScreen(){return `${studioHeading('因子研究','搜索跨数据源目录，构建自己的信号，并组合为可验证的特征集。')}<div class="v2-tabbar"><button data-v2="catalog-tab" data-id="factors" class="${v.catalogTab==='factors'?'active':''}">因子目录 <span>${count(v.catalog.total)}</span></button><button data-v2="catalog-tab" data-id="fields" class="${v.catalogTab==='fields'?'active':''}">数据库字段</button><button data-v2="catalog-tab" data-id="builder" class="${v.catalogTab==='builder'?'active':''}">构建因子</button></div>${v.catalogTab==='builder'?builder():`<div class="v2-factor-layout"><div>${v.catalogTab==='fields'?fieldBrowser():catalogBrowser()}</div><aside>${section(`当前因子组合 <span class="count-label">${s.strategy.factors.length} / 32</span>`,`<div class="v2-panel-content" data-v2-drop="recipe">${recipeGroups(true)}<div class="v2-drop-hint">拖入可研究因子，或点击列表中的 +</div>${action('group','新建研究分组','plus','ghost full')}<p class="footnote">分组用于组织研究分支；所有分组的因子将合并作为模型特征。本版不执行分组权重或独立分支回测。</p>${link('studio/targets','继续：观察与检验','arrow','primary full')}</div>`)}</aside></div>`}`;}
    function catalogBrowser(){const data=v.catalog,f=v.filters;return `<div class="v2-catalog-controls"><label class="v2-search">${i('search')}<input id="v2-factor-search" placeholder="搜索因子、公式、研究主题…" aria-label="搜索因子目录" value="${e(f.q)}"></label><div class="v2-filter-grid"><select id="v2-factor-database" aria-label="因子数据库"><option value="">所有数据库</option>${labelOptions(data.databases||['MKT','FD','PCD','PCD_DERIVED','EXT','MODEL','COMMUNITY'],f.database)}</select><select id="v2-factor-category" aria-label="因子类别"><option value="">所有类别</option>${labelOptions(data.categories||[],f.category)}</select><select id="v2-factor-availability" aria-label="因子可用状态"><option value="">所有状态</option>${labelOptions([{id:'ready',name:'可研究'},{id:'schema_only',name:'仅字段定义'},{id:'needs_mapping',name:'待映射'},{id:'unavailable',name:'暂不可用'}],f.availability)}</select></div></div><div class="v2-catalog-caption"><span>匹配 ${count(data.total)} 个定义 · 每页 ${data.pageSize||24} 个</span><span>${Object.entries(data.availabilityCounts||{}).map(([k,n])=>`${availability({status:k})} ${count(n)}`).join(' / ')}</span></div>${v.catalogError?`<div class="notice error">${e(v.catalogError)} ${action('retry-factors','重试')}</div>`:''}<div class="v2-catalog-list" aria-live="polite">${v.catalogLoading?'<div class="loading-line"><span class="spinner"></span>搜索目录…</div>':data.items.length?data.items.map(factorRow).join(''):empty('没有匹配的因子定义。可更换搜索词或数据源。')}</div>${pagination('factor-page',f.page,data.total,data.pageSize||24)}<p class="footnote">目录规模包含尚未接入观测值的定义。待映射项须先配置匹配的精确绑定或导入有效 PIT 字段，才能加入研究；目录原始状态不因此改变，覆盖与数据真实性仍在运行时核验。</p>`;}
    function factorRow(f){const used=s.strategy.factors.some(x=>x.id===f.id);return `<article class="v2-factor-row" ${canUse(f)&&f.expression?`draggable="true" data-v2-drag="factor:${e(f.id)}"`:''}><div class="v2-factor-row-main"><div class="v2-factor-title"><button class="inline-link" data-v2="factor-detail" data-id="${e(f.id)}">${e(itemName(f))}</button>${chip(f)}${contextualChip(f)}</div><p>${e(s.strategy.research?.mode==='statistical_quant'?window.AtlasQuantV4.describeFactor(f.description||f.rationale||''):f.description||f.rationale||'')}</p><div class="v2-factor-tags"><span>${e(databaseName(f.database||f.source?.database||(typeof f.source==='string'?f.source:'因子库')))}</span><span>${e(f.category||'其他')}</span>${f.lookback?`<span>${e(f.lookback)} 日回看</span>`:''}</div>${f.expression?`<code>${e(f.expression)}</code>`:''}${!ready(f)&&reason(f)?`<small class="v2-availability-reason">${e(reason(f))}</small>`:''}</div><div class="v2-factor-actions">${action('add-factor',used?'已加入':'加入',used?'check':'plus','ghost small',`data-id="${e(f.id)}" ${!canUse(f)||!f.expression||used?'disabled':''}`)}${action('edit-factor','编辑','code','subtle small',`data-id="${e(f.id)}" ${!f.expression?'disabled':''}`)}</div></article>`;}
    function fieldBrowser(){const d=v.fieldCatalog,f=v.fieldFilters;return `<div class="v2-catalog-controls"><label class="v2-search">${i('search')}<input id="v2-field-search" aria-label="搜索数据库字段" placeholder="搜索 PCD / MKT / EXT / MODEL 字段…" value="${e(f.q)}"></label><select id="v2-field-database" aria-label="字段数据库"><option value="">所有数据库</option>${labelOptions(d.databases||['MKT','FD','PCD','PCD_DERIVED','EXT','MODEL'],f.database)}</select></div><p class="v2-catalog-caption">${count(d.total)} 个字段定义；定义数量不代表已有数据观测。</p><div class="v2-catalog-list">${v.fieldLoading?'<div class="loading-line"><span class="spinner"></span>加载字段…</div>':(d.items||[]).map(x=>`<article class="v2-factor-row"><div class="v2-factor-row-main"><div class="v2-factor-title"><strong>${e(itemName(x))}</strong>${chip(x)}${contextualChip(x)}</div><p>${e(x.description||x.path||x.canonicalPath||'')}</p><code>${e(x.alias||x.field||x.key||x.id)}</code><div class="v2-factor-tags"><span>${e(databaseName(x.database||''))}</span><span>${e(x.dtype||x.type||'')}</span><span>${e(x.frequency||'频率待确认')}</span></div><small class="v2-availability-reason">${e(reason(x)||'因子生成需要可用的观测值、标的映射与发布时间。')}</small></div><div class="v2-factor-actions">${action('field-build','构建因子','plus','ghost small',`data-id="${e(x.id||x.field)}" ${canUse(x)?'':'disabled'}`)}${x.database==='PCD'?action('field-map','精确映射','link','subtle small',`data-id="${e(x.id)}"`):''}</div></article>`).join('')||empty('没有匹配的字段。')}</div>${pagination('field-page',f.page,d.total,d.pageSize||24)}`;}
    function pagination(actionId,page,total,size){return `<div class="v2-pagination"><span>第 ${page} / ${Math.max(1,Math.ceil((total||0)/size))} 页</span><div>${action(actionId,'上一页','','ghost small',`data-page="${page-1}" ${page<=1?'disabled':''}`)}${action(actionId,'下一页','','ghost small',`data-page="${page+1}" ${page*size>=total?'disabled':''}`)}</div></div>`;}
    function groups(){const gs=Array.isArray(s.strategy.graph.groups)?s.strategy.graph.groups:[];const ids=new Set(s.strategy.factors.map(f=>f.id));const included=new Set();const result=gs.map(g=>({...g,factorIds:(g.factorIds||[]).filter(id=>ids.has(id)&&!included.has(id)&&(included.add(id),true))}));const remaining=s.strategy.factors.filter(f=>!included.has(f.id)).map(f=>f.id);if(remaining.length||!result.length)result.push({id:'ungrouped',name:'我的研究信号',factorIds:remaining});return result;}
    function recipeGroups(advanced){return `<div class="v2-recipe-groups">${groups().map(g=>`<section class="v2-recipe-group" data-v2-drop="group:${e(g.id)}"><div class="v2-group-heading"><strong>${e(g.name)}</strong><span>${g.factorIds.length} ${advanced?'个因子':'个信号'}</span>${g.id!=='ungrouped'?action('remove-group','移除','close','subtle small',`data-id="${e(g.id)}" aria-label="移除分组 ${e(g.name)}"`):''}</div>${g.factorIds.map(id=>{const f=s.strategy.factors.find(f=>f.id===id),known=C.findFactor(id);return `<div class="v2-recipe-factor" ${advanced?`data-v2-drag="selected:${e(id)}"`:''}><div><strong>${e(known?.name||f.name||id)}</strong>${advanced?`<code>${e(f.expression)}</code><select aria-label="${e(known?.name||id)} 的方向" data-factor-direction="${e(id)}"><option value="1" ${f.direction===1?'selected':''}>正向</option><option value="-1" ${f.direction===-1?'selected':''}>反向</option></select><select aria-label="${e(known?.name||id)} 的分组" data-v2-factor-group="${e(id)}">${groups().map(x=>`<option value="${e(x.id)}" ${x.id===g.id?'selected':''}>${e(x.name)}</option>`).join('')}</select>`:''}</div>${legacy('remove-factor','', 'close','subtle small',`data-id="${e(id)}" aria-label="移除因子 ${e(known?.name||id)}"`)}</div>`;}).join('')||'<p class="v2-group-empty">把因子拖入这个分组</p>'}</section>`).join('')}</div>`;}
    function builder(){return `<div class="v2-two-col">${section('构建一个可解释的因子',`<div class="v2-panel-content"><label class="field"><span>因子名称</span><input id="v2-builder-name" value="${e(v.builder.name)}" maxlength="80"></label><div class="v2-builder-steps"><label class="field"><span>① 原始字段</span><select id="v2-builder-field">${labelOptions(['close','open','high','low','vol','amount','turnover_rate','pe_ttm','pb','total_mv','circ_mv'],v.builder.field)}</select></label><label class="field"><span>② 变换方法</span><select id="v2-builder-transform">${labelOptions([{id:'returns',name:'变化率'},{id:'ts_mean',name:'移动平均'},{id:'ts_std',name:'滚动波动'},{id:'delta',name:'差值'},{id:'ts_rank',name:'时间序列排名'},{id:'rank',name:'横截面排名'},{id:'zscore',name:'横截面标准分'},{id:'identity',name:'直接使用'}],v.builder.transform)}</select></label><label class="field"><span>③ 回看交易日</span><input id="v2-builder-window" type="number" min="1" max="252" value="${v.builder.window}"></label></div><div class="actions">${action('compose-expression','生成表达式','workflow')}</div><label class="field" style="margin-top:20px"><span>表达式 · 可直接修改</span><textarea id="v2-builder-expression" class="v2-expression-editor" spellcheck="false" maxlength="500">${e(v.builder.expression)}</textarea></label><label class="field"><span>输入符号</span><select id="v2-builder-direction"><option value="1" ${v.builder.direction===1?'selected':''}>正向编码 +1</option><option value="-1" ${v.builder.direction===-1?'selected':''}>反向编码 −1</option></select></label><div class="actions">${action('lint-builder',v.lintBusy?'校验中…':'校验公式','check','ghost',v.lintBusy?'disabled':'')}${action('add-custom','加入当前研究','plus','primary')}${action('builder-code','在代码区打开','code','subtle')}</div>${lintView()}</div>`)}<div>${section('从字段到因子的边界',`<div class="v2-panel-content"><div class="v2-research-flow"><div>原始观测<span>字段、单位、频率</span></div><b>↓</b><div>时点对齐<span>标的映射、发布时间</span></div><b>↓</b><div>因果变换<span>只能使用当时已知的信息</span></div><b>↓</b><div>研究特征<span>训练、验证与独立测试</span></div></div><p class="footnote">Financial DB 的目录字段必须先有真实观测值和发布时间映射，才能成为可回测的因子。表达式合法不等于数据已具备。</p></div>`)}${section('可用表达式',`<div class="v2-panel-content"><pre class="code-snippet">returns(close,20)\nts_std(returns(close,1),20)\nrank(amount / ts_mean(amount,20))\n(close - ts_mean(close,20)) / ts_std(close,20)</pre><p class="footnote">窗口 1–252；最多 500 字符。禁用未来偏移、任意代码与网络访问。</p>${legacy('contribute','贡献到开放因子社区','users')}</div>`)}</div></div>`;}
    function lintView(){if(!v.lint)return '';return `<div class="v2-lint ${v.lint.valid?'valid':'invalid'}" role="status"><strong>${v.lint.valid?'表达式语法通过':'表达式需要修改'}</strong>${v.lint.lookback!==undefined?`<p>最大回看 ${e(v.lint.lookback)} 个交易日 · 字段 ${e((v.lint.fields||[]).join(', '))}</p>`:''}${(v.lint.diagnostics||[]).map(d=>`<p>${e(typeof d==='string'?d:d.message)}</p>`).join('')}${v.lint.availability?`<p>${e(availability(v.lint))}：${e(reason(v.lint))}</p>${contextualChip(v.lint)}`:''}</div>`;}
    function targetScreen(){return flow.studioSignals();}
    function forecastPreview(){const runs=s.runs.filter(r=>['completed','complete','succeeded','success'].includes(r.status));return section('旧版逐股模型输出诊断',`<div class="v2-panel-content"><div class="v2-forecast-loader"><label class="field"><span>选择已完成研究</span><select id="v2-forecast-run" aria-label="选择预测研究记录"><option value="">最近完成的研究</option>${runs.map(r=>`<option value="${e(r.id)}" ${v.forecastRunId===r.id?'selected':''}>${e(r.name||r.strategy?.name||r.id)} · ${e(dateText(r.createdAt))}</option>`).join('')}</select></label>${action('load-forecast',v.forecastLoading?'读取中…':'读取旧诊断','chart','ghost',v.forecastLoading||!runs.length?'disabled':'')}</div>${v.forecastResult?`<p class="footnote">以下是「${e(v.forecastJob?.name||v.forecastResult.strategy?.name||'所选研究')}」的冻结记录；不随上方当前草稿的修改而变化。</p>${C.forecastReport(v.forecastResult,true)}${link('runs/'+encodeURIComponent(v.forecastJob.id),'查看完整运行报告','arrow','ghost')}`:empty(runs.length?'选择旧版已完成研究，读取冻结模型输出与误差。':'尚无旧版已完成研究；新篮子研究请查看残差与敞口报告。')}</div>`);}
    async function loadForecast(){const id=v.forecastRunId||s.runs.find(r=>['completed','complete','succeeded','success'].includes(r.status))?.id;if(!id)throw Error('还没有已完成的研究。');v.forecastLoading=true;render();try{const response=await api('/runs/'+encodeURIComponent(id));v.forecastResult=response.result||response.job?.result;v.forecastJob=response.job;v.forecastRunId=id;if(!v.forecastResult)throw Error('这条运行记录没有可读取的结果。');}finally{v.forecastLoading=false;render();}}
    function modelScreen(){if(flow.isArb())return flow.studioModels();return `${studioHeading('模型与机器学习','指定研究候选，使用同样的时间验证比较各类模型。')}<div class="v2-two-col">${section('选择方式',`<div class="v2-panel-content"><div class="v2-choice-row"><label><input type="radio" name="v2-model-mode" data-v2-model-mode="auto" ${s.strategy.model.mode==='auto'?'checked':''}><div><strong>自动比较</strong><p>在选中的候选内，使用验证期结果选择。</p></div></label><label><input type="radio" name="v2-model-mode" data-v2-model-mode="manual" ${s.strategy.model.mode==='manual'?'checked':''}><div><strong>指定模型</strong><p>只运行你选择的一个模型。</p></div></label></div><div class="v2-model-presets">${action('model-pack','轻量研究','','ghost small','data-id="light"')}${action('model-pack','稳健线性','','ghost small','data-id="linear"')}${action('model-pack','非线性探索','','ghost small','data-id="trees"')}${action('model-pack','全部候选','','ghost small','data-id="all"')}</div></div>`)}${section('进入模型的特征',`<div class="v2-panel-content"><strong>${s.strategy.factors.length} 个因子 · ${groups().length} 个研究分组</strong><p style="margin-top:10px">预测目标：${s.strategy.model.target==='forward_excess_return'?'股票池内超额收益':'未来收益'} / ${s.strategy.model.horizon} 日</p><p class="footnote">候选之间使用同样的特征与时间范围。有限的搜索空间不代表对所有机器学习方法的全局最优。</p></div>`)}</div><div class="v2-model-grid">${Object.entries(models).map(([id,[name,description,family]])=>`<label class="v2-model-card ${s.strategy.model.candidates.includes(id)?'selected':''}"><input type="${s.strategy.model.mode==='manual'?'radio':'checkbox'}" name="candidate" data-candidate="${id}" ${s.strategy.model.candidates.includes(id)?'checked':''}><span class="v2-model-family">${family}</span><h2>${name}</h2><p>${description}</p><span class="v2-model-selection">${s.strategy.model.candidates.includes(id)?'已选择':'加入比较'}</span></label>`).join('')}</div>${section('预处理流水线',`<div class="v2-panel-content v2-preprocess"><label class="check-label"><input type="checkbox" data-config="preprocess.winsorize" ${s.strategy.preprocess.winsorize?'checked':''}><span>截尾去极值<small>阈值仅从训练样本拟合。</small></span></label><label class="check-label"><input type="checkbox" data-config="preprocess.standardize" ${s.strategy.preprocess.standardize?'checked':''}><span>标准化<small>验证与测试复用训练集参数。</small></span></label>${link('studio/validation','继续：时间验证','arrow','primary')}</div>`)}`;}
    function validationScreen(){return flow.studioValidation();}
    function portfolioScreen(){return flow.studioExecution();}
    function reportScreen(){return `${studioHeading('研究报告','每次运行保留策略快照、数据来源、模型选择与最终独立测试。')}${C.runsView()}`;}
    function community(){const list=C.factors().filter(f=>f.source==='community'||f.forkOf||f.isOwner||f.builtin===false);return `${header('OPEN FACTOR COMMUNITY','一起构建开放因子库。','分享公式、研究思路与来源，让每个想法都可以被理解和复用。',legacy('contribute','贡献一个因子','plus','primary'))}<div class="v2-community-banner"><div>${i('users')}<h2>定义公开，数据与策略保持私有。</h2><p>发布因子时，你分享的是公式与研究说明。每个贡献保留作者、许可证、版本与 Fork 关系。</p></div>${link('studio/factors','探索完整因子目录','layers')}</div><div class="v2-catalog-list">${list.length?list.map(factorRow).join(''):empty('还没有社区贡献。创建一个可解释的因子，发布你的第一个研究想法。')}</div><p class="footnote">社区因子默认未经审阅。加入研究前检查可用字段、发布时间、未来信息与许可证。</p>`;}
    function codeScreen({embedded=false}={}){const lang=v.editorLanguage,code=lang==='json'?(v.code.json||JSON.stringify(s.strategy,null,2)):v.code[lang];return `${embedded?'':studioHeading('代码与 AI 审阅','自己编辑研究逻辑，先检查，再明确应用建议。')}${codeProjects()}<div class="v2-code-workspace"><section class="panel v2-code-panel"><div class="v2-code-tabs">${[['dsl','Factor DSL'],['python','Python 研究'],['json','策略 JSON']].map(([id,label])=>`<button data-v2="language" data-id="${id}" class="${lang===id?'active':''}">${i(id==='json'?'workflow':'code')}${label}</button>`).join('')}</div><div class="v2-code-caption"><span>${lang==='dsl'?'factor.atlas':lang==='python'?'research.py':'strategy.json'}</span><span>${lang==='python'?'浏览器隔离运行 · 最长 120 秒':lang==='dsl'?'因果表达式 · 最多 500 字符':'编辑后需主动应用到当前策略'}</span></div><label class="sr-only" for="v2-code-editor">${lang} 代码编辑器</label><textarea id="v2-code-editor" class="v2-code-editor" spellcheck="false" autocomplete="off" autocapitalize="off" aria-label="${lang} 代码编辑器">${e(code)}</textarea><div class="v2-code-actions">${lang==='python'?action('python-run',v.pythonBusy?'运行中…':'运行 Python','play','primary',v.pythonBusy?'disabled':''):lang==='dsl'?action('lint-code',v.lintBusy?'校验中…':'校验表达式','check','primary',v.lintBusy?'disabled':''):action('apply-json','检查并应用策略','check','primary')}${lang!=='json'?action('review-manual',v.reviewBusy?'检查中…':'规则检查','shield','ghost',v.reviewBusy?'disabled':''):''}${lang!=='json'?action('review-ai','AI 审阅','spark','ghost',v.reviewBusy?'disabled':''):''}${action('export-code','导出代码','download','subtle')}${lang==='dsl'?action('code-to-factor','作为因子加入','plus','ghost'):''}</div>${lang==='dsl'?lintView():''}${lang==='python'?`<div class="v2-python-data"><span>${i('database')}${s.dataset?`data 已绑定 ${count(s.dataset.rows.length)} 行导入数据`:'data 为空：导入数据后可在 Python 中读取'}</span>${legacy('import-data','导入数据','upload','subtle small')}</div><div class="v2-output"><h3>运行输出</h3>${v.pythonOutput?`<pre>${e(v.pythonOutput.error||v.pythonOutput.stdout||'（无标准输出）')}</pre>${v.pythonOutput.stderr?`<pre class="error">${e(v.pythonOutput.stderr)}</pre>`:''}${v.pythonOutput.results!==undefined?`<h4>result</h4><pre>${e(typeof v.pythonOutput.results==='string'?v.pythonOutput.results:JSON.stringify(v.pythonOutput.results,null,2))}</pre>`:''}${v.pythonOutput.elapsedMs!==undefined?`<small>${e(v.pythonOutput.elapsedMs)} ms</small>`:''}`:'<p>尚未运行。首次启动将加载隔离的 Python 运行时。</p>'}</div>`:''}</section><aside class="v2-review-panel">${reviewPanel()}${section('研究脚本的作用',`<div class="v2-panel-content"><p>Python 用于你自己的数据探索。运行输出不会自动修改因子或策略。</p><p class="footnote">受支持的 Factor DSL 才会进入服务器回测引擎。代码审阅建议必须由你明确应用；审阅通过不代表策略有效。</p><div class="v2-research-flow"><div>编辑<span>表达式 / Python / 配置</span></div><b>↓</b><div>校验与审阅<span>语法、时序与可用数据</span></div><b>↓</b><div>明确应用<span>查看原代码与建议差异</span></div></div></div>`)}</aside></div>`;}
    function codeProjects(){return `<div class="v2-project-bar"><label class="field"><span>代码项目</span><select id="v2-code-project" aria-label="打开已保存代码项目"><option value="">未保存的本地草稿</option>${v.projects.map(p=>`<option value="${e(p.id)}" ${p.id===v.projectId?'selected':''}>${e(p.name)} · ${e(p.language)} · v${e(p.version)}</option>`).join('')}</select></label><label class="field"><span>项目名称</span><input id="v2-project-name" value="${e(v.projectName)}" maxlength="80"></label>${action('save-code',v.projectSaving?'保存中…':v.projectId?'保存新版本':'保存代码项目','save','ghost',v.projectSaving||v.editorLanguage==='json'?'disabled':'')}${action('new-code','新草稿','plus','subtle')}</div>`;}
    async function saveCode(){if(!v.projectName.trim())throw Error('请填写代码项目名称。');if(v.editorLanguage==='json')throw Error('策略 JSON 请使用页面顶部的保存按钮。');v.projectSaving=true;render();try{const response=await api(v.projectId?'/code/projects/'+encodeURIComponent(v.projectId):'/code/projects',{method:v.projectId?'PUT':'POST',body:JSON.stringify({name:v.projectName,language:v.editorLanguage,code:v.code[v.editorLanguage],...(v.projectId?{version:v.projectVersion}:{})})});const p=response.item;v.projectId=p.id;v.projectVersion=p.version;v.projects=[p,...v.projects.filter(x=>x.id!==p.id)];toast('代码项目已保存到私有工作区。');}finally{v.projectSaving=false;render();}}
    function reviewPanel(){const r=v.review;if(!r)return section('审阅助手',`<div class="v2-panel-content"><div class="v2-review-empty">${i('spark')}<h3>给研究多一双眼睛。</h3><p>规则检查定位表达式、数据依赖与常见风险；AI 审阅会在真实服务返回后显示结果。</p><p>系统不会自动修改你的代码。</p></div></div>`);return section(r.providerExecuted?'AI 审阅结果':'规则检查结果',`<div class="v2-panel-content"><span class="v2-status ${r.providerExecuted?'ready':''}"><i></i>${r.providerExecuted?'已调用 AI 服务':'未调用 AI 服务'}</span><p class="v2-review-summary">${e(r.summary||'检查完成')}</p>${(r.findings||[]).map(f=>`<article class="v2-finding ${e(f.severity||'info')}"><span>${e(f.severity||'info')}${f.line?` · L${e(f.line)}`:''}</span><p>${e(f.message)}</p>${f.suggestion?`<small>${e(f.suggestion)}</small>`:''}</article>`).join('')}${(r.patches||[]).map((p,index)=>`<article class="v2-patch"><h3>${e(p.title||`建议 ${index+1}`)}</h3><p>${e(p.reason||'')}</p><label>当前代码</label><pre class="v2-diff-before">${e(p.before)}</pre><label>建议修改</label><pre class="v2-diff-after">${e(p.after)}</pre>${action('apply-patch',v.applied.has(index)?'已应用':'应用此建议','check','ghost small',`data-index="${index}" ${v.applied.has(index)?'disabled':''}`)}</article>`).join('')}</div>`);}
    async function initialize(){
      v.errors=[];const endpoints=[['universes','/universes?category=index&pageSize=12'],['universeStats','/universes?pageSize=1'],['presets','/research-presets'],['sources','/data-sources'],['projects','/code/projects']];
      const results=await Promise.allSettled(endpoints.map(([,p])=>api(p)));
      results.forEach((r,index)=>{const key=endpoints[index][0];if(r.status==='fulfilled'){if(key==='universeStats'){v.universeAllTotal=r.value.total||0;}else if(key==='presets')v.presets={goals:[],packs:[],strategies:[],...r.value};else {v[key]=r.value.items||[];if(key==='sources'){v.sourceArchitecture=r.value.architecture||null;v.sourceAdapters=r.value.adapters||[];}if(key==='universes'){v.universeTotal=r.value.total||0;v.featuredUniverses=v.universes.filter(x=>x.curated||x.recommended||x.category==='index');v.universeCategories=r.value.categories||[];}}}else v.errors.push(`${{universes:'股票池',universeStats:'股票池统计',presets:'精选组合',sources:'数据源',projects:'代码项目'}[key]}：${r.reason.message}`);});v.ready=true;render();await Promise.allSettled([loadFactors(),flow.initialize().catch(err=>{v.errors.push('集合筛选：'+err.message);render();})]);
    }
    let universeRequest=0;
    async function loadUniverses(){const request=++universeRequest;v.universeLoading=true;render();try{const response=await api('/universes?'+new URLSearchParams({q:v.universeQuery,category:v.universeCategory,page:v.universePage,pageSize:12}));if(request!==universeRequest)return;v.universes=response.items||[];v.universeTotal=response.total||0;if(!v.universeQuery&&v.universeCategory==='all')v.universeAllTotal=v.universeTotal;v.universeCategories=response.categories||[];}catch(err){toast(err.message,true);}finally{if(request===universeRequest){v.universeLoading=false;render();}}}
    async function loadUniversesWithFocus(id){const pos=document.getElementById(id)?.selectionStart;await loadUniverses();const input=document.getElementById(id);if(input&&document.activeElement===document.body){input.focus();if(pos!==undefined)input.setSelectionRange(pos,pos);}}
    let factorRequest=0,fieldRequest=0;
    async function loadFactors(){const request=++factorRequest;v.catalogLoading=true;v.catalogError='';render();try{const q=new URLSearchParams({...v.filters,pageSize:'24'});const d=await api('/factor-catalog?'+q);if(request!==factorRequest)return;v.catalog={items:[],...d};if(!v.filters.q&&!v.filters.category&&!v.filters.database&&!v.filters.availability)v.catalogSummary={total:d.total,ready:d.availabilityCounts?.ready};const byId=new Map(C.factors().map(f=>[f.id,f]));for(const f of v.catalog.items)byId.set(f.id,f);s.factors=[...byId.values()];}catch(err){if(request!==factorRequest)return;v.catalogError=err.message;}finally{if(request===factorRequest){v.catalogLoading=false;render();}}}
    async function loadFields(){const request=++fieldRequest;v.fieldLoading=true;render();try{const d=await api('/fields?'+new URLSearchParams({...v.fieldFilters,pageSize:'24'}));if(request!==fieldRequest)return;v.fieldCatalog={items:[],...d};}catch(err){toast(err.message,true);}finally{if(request===fieldRequest){v.fieldLoading=false;render();}}}
    function cacheFactors(items){const m=new Map(C.factors().map(x=>[x.id,x]));items.forEach(x=>m.set(x.id,x));s.factors=[...m.values()];}
    async function resolveFactors(ids){const found=[];for(const value of ids){if(typeof value==='object'&&value.expression){found.push(value);continue;}const id=typeof value==='string'?value:value.id;let f=C.findFactor(id);if(!f?.expression){const r=await api('/factors/'+encodeURIComponent(id));f=r.item||r;}if(!f?.expression)throw Error(`无法读取因子 ${id}`);found.push(f);}cacheFactors(found);return found;}
    function addFeatures(items,groupName){const unique=items.filter(x=>!s.strategy.factors.some(f=>f.id===x.id));if(s.strategy.factors.length+unique.length>32)throw Error('一次研究最多组合 32 个因子，请先移除部分因子。');for(const f of items)if(!canUse(f)||!f.expression)throw Error(`${itemName(f)} 还不具备可研究的数据条件。`);cacheFactors(items);s.strategy.factors.push(...unique.map(f=>({id:f.id,expression:f.expression,direction:Number(f.direction)===-1?-1:1})));if(groupName&&s.strategy.graph&&(s.strategy.graph.groups?.length||0)<12){const id='group_'+Date.now().toString(36);s.strategy.graph.groups ||= [];s.strategy.graph.groups.push({id,name:groupName,factorIds:unique.map(f=>f.id)});}persistDraft();render();toast(unique.length?`已加入 ${unique.length} 个研究信号。`:'这些信号已在当前研究中。');}
    async function selectUniverse(id){return flow.selectUniverse(id);}
    async function addPack(id){const p=v.presets.packs.find(x=>x.id===id);if(!p)throw Error('未找到这个研究模块。');const fs=await resolveFactors(p.factors||p.factorIds||[]);if(!fs.length)throw Error('这个模块没有可执行的因子定义。');addFeatures(fs,itemName(p));}
    function moveFactor(id,groupId){s.strategy.graph.groups ||= [];for(const g of s.strategy.graph.groups)g.factorIds=(g.factorIds||[]).filter(x=>x!==id);if(groupId!=='ungrouped'){const group=s.strategy.graph.groups.find(g=>g.id===groupId);if(group)group.factorIds.push(id);}persistDraft();render();}
    async function lint(expression){v.lintBusy=true;v.lint=null;render();try{v.lint=await api('/expressions/lint',{method:'POST',body:JSON.stringify({expression,dataSource:s.dataSource,...(s.dataset?{fields:Object.keys(s.dataset.rows[0]||{})}:{})})});return v.lint;}finally{v.lintBusy=false;render();}}
    async function custom(expression,name){const result=await lint(expression);if(!result.valid)throw Error('请先修正公式中的问题。');if(result.availability&&!canUse(result))throw Error(reason(result)||'表达式所需数据尚未就绪。');const id='custom_'+Date.now().toString(36);addFeatures([{id,name:name||'自定义因子',expression,direction:v.builder.direction,availability:result.availability||{status:'ready'},fields:result.fields}]);}
    function persistEditor(){try{localStorage.setItem('atlas-quant-editor-v2',JSON.stringify({code:{dsl:v.code.dsl,python:v.code.python}}));}catch{}}
    async function review(mode){const lang=v.editorLanguage;if(lang==='json')return;v.reviewBusy=true;v.review=null;v.applied.clear();render();try{const response=await api('/code/review',{method:'POST',timeoutMs:90000,body:JSON.stringify({language:lang,code:v.code[lang],strategy:s.strategy,mode})});v.review=response.review||response;v.review.language=lang;v.review.original=v.code[lang];}finally{v.reviewBusy=false;render();}}
    async function pythonRun(){if(!window.AtlasPython?.run)throw Error('Python 运行时尚未加载，请重试页面或稍后再试。');v.pythonBusy=true;v.pythonOutput=null;render();try{v.pythonOutput=await window.AtlasPython.run({code:v.code.python,rows:s.dataset?.rows||[],timeoutMs:120000});}catch(err){v.pythonOutput={error:err.message};}finally{v.pythonBusy=false;render();}}
    function showCatalogDetail(id){const f=C.findFactor(id);if(!f)return;C.openModal(itemName(f),`<div class="tag-row">${chip(f)}${contextualChip(f)}<span class="tag">${e(f.database||f.source?.database||'因子库')}</span><span class="tag">${e(f.category||'其他')}</span></div><p style="margin-top:18px">${e(f.description||f.rationale||'')}</p>${f.expression?`<pre class="code-snippet">${e(f.expression)}</pre>`:''}<dl class="definition-list" style="margin-top:20px"><dt>定义 ID</dt><dd>${e(f.id)}</dd><dt>数据状态</dt><dd>${e(availability(f))}</dd><dt>数据要求</dt><dd>${e(reason(f)||'运行时仍需检查字段与有效样本覆盖。')}</dd><dt>字段</dt><dd>${e((f.fields||f.requiredFields||[]).join(', '))}</dd><dt>作者 / 来源</dt><dd>${e(f.author||f.provenance?.source||'Atlas Quant')}</dd><dt>许可证</dt><dd>${e(f.license||'请查看定义来源')}</dd></dl><div class="form-footer">${f.expression?action('edit-factor','编辑公式','code','ghost',`data-id="${e(id)}"`):''}${f.expression?legacy('fork-factor','Fork / 贡献','fork','ghost',`data-id="${e(id)}"`):''}${action('add-factor','加入研究','plus','primary',`data-id="${e(id)}" ${!canUse(f)||!f.expression?'disabled':''}`)}</div>`,true);}
    async function handle(button){const a=button.dataset.v2,id=button.dataset.id;if(await flow.handle(button))return;
      if(a==='reload-catalogs')return initialize();
      if(a==='universe')return selectUniverse(id);
      if(a==='member-page'){v.membersPage=Number(button.dataset.page);render();}
      if(a==='universe-page'){v.universePage=Number(button.dataset.page);return loadUniverses();}
      if(a==='pack')return addPack(id);
      if(a==='fresh')return flow.handle({dataset:{v2:'new-arb'}});
      if(a==='goal'){const g=v.presets.goals.find(x=>x.id===id);v.goal=id;if(g?.model)s.strategy.model={...s.strategy.model,...g.model};if(g?.horizon)s.strategy.model.horizon=Number(g.horizon);if(g?.target)s.strategy.model.target=g.target;if(g?.portfolio)s.strategy.portfolio={...s.strategy.portfolio,...g.portfolio};persistDraft();render();}
      if(a==='preset'){const p=v.presets.strategies.find(x=>x.id===id);if(!p)throw Error('未找到研究组合。');const strategy=p.strategy||p.config;if(!strategy)throw Error('研究组合没有可执行配置。');const universe=clone(s.strategy.universe);s.strategy=normalizeStrategy(clone(strategy));s.strategy.universe=universe;s.strategy.research.baseline={id:p.id,name:p.name};s.strategyId=null;s.strategyVersion=null;persistDraft();C.navigate('research/baseline');render();}
      if(a==='source'){s.dataSource=id;persistDraft();render();if(id==='upload'&&!s.dataset)C.importData();}
      if(a==='catalog-tab'){v.catalogTab=id;render();if(id==='fields')await loadFields();}
      if(a==='retry-factors')return loadFactors();
      if(a==='factor-page'){v.filters.page=Number(button.dataset.page);return loadFactors();}
      if(a==='field-page'){v.fieldFilters.page=Number(button.dataset.page);return loadFields();}
      if(a==='add-factor'){const f=C.findFactor(id);if(!f)throw Error('未找到因子定义。');C.closeModal();addFeatures([f]);}
      if(a==='factor-detail')showCatalogDetail(id);
      if(a==='edit-factor'){const f=C.findFactor(id);v.builder={...v.builder,name:`${itemName(f)} · 我的版本`,expression:f.expression,direction:f.direction||1};v.lint=null;v.catalogTab='builder';if(C.quantFeatureTab)C.quantFeatureTab('builder');C.closeModal();location.hash=s.strategy.research?.mode==='statistical_quant'?'quant/studio/state':'studio/factors';render();}
      if(a==='group'){if((s.strategy.graph.groups?.length||0)>=12)throw Error('最多保留 12 个研究分组。');C.openModal('新建研究分组',`<form id="v2-group-form"><label class="field"><span>分组名称</span><input name="name" maxlength="60" required placeholder="例如：估值分支 / 趋势分支"></label><p>分组组织研究思路，模型仍使用各组因子的合并特征。</p><div class="form-footer"><button class="btn primary" type="submit">创建分组</button></div></form>`);}
      if(a==='remove-group'){s.strategy.graph.groups=(s.strategy.graph.groups||[]).filter(g=>g.id!==id);persistDraft();render();}
      if(a==='field-map'){const f=v.fieldCatalog.items.find(x=>x.id===id);v.mapping={alias:f.alias||'',fieldId:f.id,unitCode:f.unitCode||f.unit||'',records:'[]'};location.hash=s.strategy.research?.mode==='statistical_quant'?'quant/studio/universe':'studio/data';render();}
      if(a==='remove-binding'){delete s.strategy.dataBindings.pcd[id];persistDraft();render();}
      if(a==='field-build'){const f=v.fieldCatalog.items.find(x=>(x.id||x.field)===id);if(!canUse(f))throw Error('这个字段需要匹配的精确绑定或已导入的 PIT 数据。');v.builder.field=f.alias||f.field||f.key||f.id;v.builder.expression=v.builder.field;v.builder.name=`${itemName(f)} 因子`;v.catalogTab='builder';render();}
      if(a==='compose-expression'){const {field:f,transform:t,window:w}=v.builder;if(!Number.isInteger(w)||w<1||w>252)throw Error('回看窗口需为 1–252 的整数。');v.builder.expression=t==='identity'?f:['rank','zscore'].includes(t)?`${t}(${f})`:`${t}(${f},${w})`;v.lint=null;render();}
      if(a==='lint-builder')return lint(v.builder.expression);
      if(a==='add-custom')return custom(v.builder.expression,v.builder.name);
      if(a==='builder-code'){v.code.dsl=v.builder.expression;v.editorLanguage='dsl';persistEditor();location.hash=s.strategy.research?.mode==='statistical_quant'?'quant/studio/code':'studio/code';}
      if(a==='repair-graph'){s.strategy.graph={...C.defaultGraph(),groups:s.strategy.graph?.groups||[]};persistDraft();render();toast('流程连接已修复，研究分组与参数保留。');}
      if(a==='load-forecast')return loadForecast();
      if(a==='target'){s.strategy.model.target=id;persistDraft();render();}
      if(a==='horizon'){s.strategy.model.horizon=Number(id);persistDraft();render();}
      if(a==='model-pack'){const packs={light:['factor_score','ridge','elastic_net'],linear:['factor_score','ridge','elastic_net','bayesian_ridge','huber'],trees:['factor_score','hist_gradient_boosting','random_forest','extra_trees'],all:Object.keys(models)};s.strategy.model.mode='auto';s.strategy.model.candidates=packs[id];persistDraft();render();}
      if(a==='language'){v.editorLanguage=id;if(v.projects.find(x=>x.id===v.projectId)?.language!==id){v.projectId=null;v.projectVersion=null;}v.lint=null;if(id==='json'&&!v.code.json)v.code.json=JSON.stringify(s.strategy,null,2);render();}
      if(a==='lint-code')return lint(v.code.dsl);
      if(a==='review-manual')return review('manual');
      if(a==='review-ai')return review('ai');
      if(a==='python-run')return pythonRun();
      if(a==='save-code')return saveCode();
      if(a==='new-code'){v.projectId=null;v.projectVersion=null;v.projectName='我的研究脚本';v.review=null;render();}
      if(a==='apply-patch'){const index=Number(button.dataset.index),p=v.review?.patches?.[index],lang=v.review?.language;if(!p||!lang)throw Error('审阅建议已失效。');if(!p.before||!v.code[lang].includes(p.before))throw Error('代码已经变化，原片段不再匹配，请重新审阅。');if(v.code[lang].indexOf(p.before)!==v.code[lang].lastIndexOf(p.before))throw Error('匹配了多个片段，请手动修改或重新审阅，避免应用到错误位置。');v.code[lang]=v.code[lang].replace(p.before,p.after);v.applied.add(index);persistEditor();render();toast('已应用这一条修改。请重新校验或运行。');}
      if(a==='code-to-factor')return custom(v.code.dsl,v.builder.name);
      if(a==='apply-json'){let raw;try{raw=JSON.parse(v.code.json);}catch{throw Error('JSON 语法无效，请检查逗号与括号。');}const candidate=normalizeStrategy(raw),previous=s.strategy;s.strategy=candidate;const errors=C.validateStrategy(false);if(errors.length){s.strategy=previous;throw Error(errors.join('；'));}persistDraft();render();toast('策略 JSON 已校验并应用。');}
      if(a==='export-code'){const lang=v.editorLanguage;C.download(`atlas-research.${{dsl:'atlas',python:'py',json:'json'}[lang]}`,lang==='json'?(v.code.json||JSON.stringify(s.strategy,null,2)):v.code[lang],'text/plain;charset=utf-8');}
    }
    let searchTimer;
    function bind(){bindDrags();}
    document.addEventListener('click',event=>{const button=event.target.closest('[data-v2]');if(!button||button.disabled)return;event.preventDefault();Promise.resolve(handle(button)).catch(err=>toast(err.message,true));});
    document.addEventListener('submit',event=>{if(event.target.id==='v2-mapping-form'){event.preventDefault();try{const values=Object.fromEntries(new FormData(event.target));let records;try{records=JSON.parse(values.records);}catch{throw Error('记录映射需要有效的 JSON 数组。');}if(!Array.isArray(records)||!records.length||records.length>50)throw Error('需要 1–50 条精确记录映射。');if(records.some(r=>!/^\d{6}\.(SH|SZ)$/.test(r.ts_code)||typeof r.entityId!=='string'||!r.entityId.trim()||typeof r.recordId!=='string'||!r.recordId.trim()))throw Error('每条记录需要真实 ts_code、entityId 和 recordId。');s.strategy.dataBindings ||= {};s.strategy.dataBindings.pcd ||= {};if(!s.strategy.dataBindings.pcd[values.alias]&&Object.keys(s.strategy.dataBindings.pcd).length>=32)throw Error('最多绑定 32 个 PCD 字段。');s.strategy.dataBindings.pcd[values.alias]={fieldId:values.fieldId.trim(),unitCode:values.unitCode.trim(),records};v.mapping={alias:'',fieldId:'',unitCode:'',records:'[]'};persistDraft();render();toast('绑定配置已保存。实际记录与历史可用性尚待运行核验。');}catch(err){toast(err.message,true);}return;}if(event.target.id!=='v2-group-form')return;event.preventDefault();const name=new FormData(event.target).get('name').trim();if(!name)return;s.strategy.graph.groups ||= [];s.strategy.graph.groups.push({id:'group_'+Date.now().toString(36),name,factorIds:[]});persistDraft();C.closeModal();render();});
    document.addEventListener('input',event=>{const el=event.target;flow.onInput(el);if(el.closest('#v2-mapping-form')&&['alias','fieldId','unitCode','records'].includes(el.name))v.mapping[el.name]=el.value;
      if(el.id==='v2-member-search'){v.membersQuery=el.value;v.membersPage=1;clearTimeout(searchTimer);searchTimer=setTimeout(()=>rerenderPreservingFocus(el.id),220);}
      if(el.id==='v2-universe-search'){v.universeQuery=el.value;v.universePage=1;clearTimeout(searchTimer);searchTimer=setTimeout(()=>loadUniversesWithFocus(el.id),300);}
      if(el.id==='v2-factor-search'){v.filters.q=el.value;v.filters.page=1;clearTimeout(searchTimer);searchTimer=setTimeout(()=>loadFactorsWithFocus(el.id),300);}
      if(el.id==='v2-field-search'){v.fieldFilters.q=el.value;v.fieldFilters.page=1;clearTimeout(searchTimer);searchTimer=setTimeout(()=>loadFieldsWithFocus(el.id),300);}
      const builderMap={'v2-builder-name':'name','v2-builder-expression':'expression','v2-builder-window':'window'};if(builderMap[el.id]){v.builder[builderMap[el.id]]=el.type==='number'?Number(el.value):el.value;if(el.id==='v2-builder-expression')v.lint=null;}
      if(el.id==='v2-project-name')v.projectName=el.value;
      if(el.id==='v2-code-editor'){v.code[v.editorLanguage]=el.value;persistEditor();}
    });
    document.addEventListener('change',event=>{const el=event.target;try{flow.onChange(el);}catch(err){toast(err.message,true);}
      if(el.id==='v2-universe-category'){v.universeCategory=el.value;v.universePage=1;loadUniverses();}
      const factorMap={'v2-factor-category':'category','v2-factor-database':'database','v2-factor-availability':'availability'};if(factorMap[el.id]){v.filters[factorMap[el.id]]=el.value;v.filters.page=1;loadFactors();}
      if(el.id==='v2-field-database'){v.fieldFilters.database=el.value;v.fieldFilters.page=1;loadFields();}
      const builderMap={'v2-builder-field':'field','v2-builder-transform':'transform','v2-builder-direction':'direction'};if(builderMap[el.id])v.builder[builderMap[el.id]]=el.id==='v2-builder-direction'?Number(el.value):el.value;
      if(el.id==='v2-forecast-run')v.forecastRunId=el.value;
      if(el.id==='v2-code-project'){const p=v.projects.find(x=>x.id===el.value);if(p){v.projectId=p.id;v.projectVersion=p.version;v.projectName=p.name;v.editorLanguage=p.language;v.code[p.language]=p.code;v.review=null;persistEditor();render();}}
      if(el.dataset.v2ModelMode){s.strategy.model.mode=el.dataset.v2ModelMode;if(s.strategy.model.mode==='manual')s.strategy.model.candidates=[s.strategy.model.candidates[0]||'factor_score'];persistDraft();render();}
      if(el.dataset.v2Member){const code=el.dataset.v2Member;if(el.checked){if(s.strategy.universe.symbols.length>=50){el.checked=false;toast('本次研究最多 50 只；请先取消另一只标的。',true);return;}s.strategy.universe.symbols.push(code);}else s.strategy.universe.symbols=s.strategy.universe.symbols.filter(x=>x!==code);persistDraft();}
      if(el.dataset.v2FactorGroup)moveFactor(el.dataset.v2FactorGroup,el.value);
      if(el.dataset.candidate||el.dataset.config){if(isStudio()&&['targets','models','portfolio','validation'].includes(stage()))setTimeout(render,0);}
    });
    document.addEventListener('keydown',event=>{if(event.target.id==='v2-code-editor'&&event.key==='Tab'){event.preventDefault();const el=event.target,start=el.selectionStart;el.setRangeText('    ',start,el.selectionEnd,'end');v.code[v.editorLanguage]=el.value;persistEditor();}});
    function rerenderPreservingFocus(id){const old=document.getElementById(id),pos=old?.selectionStart;render();const input=document.getElementById(id);input?.focus();if(pos!==undefined)input?.setSelectionRange(pos,pos);}
    async function loadFactorsWithFocus(id){const pos=document.getElementById(id)?.selectionStart;await loadFactors();const input=document.getElementById(id);if(input&&document.activeElement===document.body){input.focus();if(pos!==undefined)input.setSelectionRange(pos,pos);}}
    async function loadFieldsWithFocus(id){const pos=document.getElementById(id)?.selectionStart;await loadFields();const input=document.getElementById(id);if(input&&document.activeElement===document.body){input.focus();if(pos!==undefined)input.setSelectionRange(pos,pos);}}
    let nativeDrag=null;
    document.addEventListener('dragstart',event=>{const el=event.target.closest('[data-v2-drag][draggable="true"]');if(!el)return;nativeDrag=el.dataset.v2Drag;event.dataTransfer?.setData('application/x-atlas-factor',nativeDrag);if(event.dataTransfer)event.dataTransfer.effectAllowed='copy';el.classList.add('sq-native-dragging');});
    document.addEventListener('dragover',event=>{const drop=event.target.closest('[data-v2-drop]');if(drop&&(nativeDrag||Array.from(event.dataTransfer?.types||[]).includes('application/x-atlas-factor'))){event.preventDefault();if(event.dataTransfer)event.dataTransfer.dropEffect='copy';drop.classList.add('sq-drop-active');}});
    document.addEventListener('dragleave',event=>{const drop=event.target.closest('[data-v2-drop]');if(drop&&!drop.contains(event.relatedTarget))drop.classList.remove('sq-drop-active');});
    document.addEventListener('drop',event=>{const drop=event.target.closest('[data-v2-drop]'),payload=event.dataTransfer?.getData('application/x-atlas-factor')||nativeDrag;if(!drop||!payload)return;event.preventDefault();nativeDrag=null;document.querySelectorAll('.sq-drop-active,.sq-native-dragging').forEach(x=>x.classList.remove('sq-drop-active','sq-native-dragging'));const [kind,...rest]=payload.split(':'),id=rest.join(':');if(kind!=='factor')return;const factor=C.findFactor(id);if(!factor)return;try{addFeatures([factor]);}catch(err){toast(err.message,true);}});
    document.addEventListener('dragend',()=>{nativeDrag=null;document.querySelectorAll('.sq-drop-active,.sq-native-dragging').forEach(x=>x.classList.remove('sq-drop-active','sq-native-dragging'));});
    function bindDrags(){document.querySelectorAll('[data-v2-drag]').forEach(el=>{el.addEventListener('pointerdown',event=>{if(el.draggable||event.button!==0||event.pointerType==='touch'||event.target.closest('button,a,input,select,textarea'))return;const start={x:event.clientX,y:event.clientY},payload=el.dataset.v2Drag;let dragging=false,ghost=null,drop=null;const move=ev=>{if(!dragging&&Math.hypot(ev.clientX-start.x,ev.clientY-start.y)>8){dragging=true;ghost=document.createElement('div');ghost.className='factor-drag-ghost';ghost.textContent=el.querySelector('h3,strong,.inline-link')?.textContent||'研究模块';document.body.append(ghost);el.setPointerCapture?.(event.pointerId);}if(!dragging)return;ev.preventDefault();ghost.style.left=ev.clientX+12+'px';ghost.style.top=ev.clientY+12+'px';document.querySelectorAll('.v2-drop-active').forEach(x=>x.classList.remove('v2-drop-active'));drop=document.elementFromPoint(ev.clientX,ev.clientY)?.closest('[data-v2-drop]');drop?.classList.add('v2-drop-active');};const end=ev=>{el.removeEventListener('pointermove',move);el.removeEventListener('pointerup',end);el.removeEventListener('pointercancel',cancel);ghost?.remove();document.querySelectorAll('.v2-drop-active').forEach(x=>x.classList.remove('v2-drop-active'));if(!dragging||!drop)return;const [kind,...rest]=payload.split(':'),id=rest.join(':'),target=drop.dataset.v2Drop;Promise.resolve().then(async()=>{if(kind==='pack')return addPack(id);if(kind==='universe')return selectUniverse(id);if(kind==='selected'&&target.startsWith('group:'))return moveFactor(id,target.slice(6));if(kind==='factor'){addFeatures([C.findFactor(id)]);if(target.startsWith('group:'))moveFactor(id,target.slice(6));}}).catch(err=>toast(err.message,true));};const cancel=()=>{el.removeEventListener('pointermove',move);el.removeEventListener('pointerup',end);el.removeEventListener('pointercancel',cancel);ghost?.remove();document.querySelectorAll('.v2-drop-active').forEach(x=>x.classList.remove('v2-drop-active'));};el.addEventListener('pointermove',move,{passive:false});el.addEventListener('pointerup',end);el.addEventListener('pointercancel',cancel);});});}
    return {render:renderApp,bind,initialize,flow,catalogBrowser,builder,fieldBrowser,mappingEditor,loadFields,renderScreen:(id,options={})=>id==='community'?community():id==='code'?codeScreen(options):studioScreen(id)};
  }};
})();
